services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vishwakarma
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "vishwakarma" ]
      interval: 20s
      retries: 5
      start_period: 5s
      timeout: 10s
volumes:
  db-data:
    driver: local