services:
  main:
    container_name: vsd-server-main
    image: vsd-server
    command: sh -c "cd server && node dist/apps/main/main.js"
    restart: always
    volumes:
      - assets:/home/app/assets
    env_file:
      - main.env
    environment:
      API_PORT: '3330'
    ports:
      - "8001:3330"
  event:
    container_name: vsd-server-event
    image: vsd-server
    command: sh -c "cd server && node -r dist/apps/event/main.js"
    restart: always
    depends_on:
      - main
    volumes:
      - assets:/home/app/assets
    env_file:
      - event.env
    environment:
      API_PORT: '3331'
    ports:
      - "8002:3331"
  family:
    container_name: vsd-server-family
    image: vsd-server
    command: sh -c "cd server && node -r dist/apps/family/main.js"
    restart: always
    depends_on:
      - main
    volumes:
      - assets:/home/app/assets
    env_file:
      - family.env
    ports:
      - "8003:3332"
  job:
    container_name: vsd-server-job
    image: vsd-server
    command: sh -c "cd server && node -r dist/apps/job/main.js"
    restart: always
    depends_on:
      - main
    volumes:
      - assets:/home/app/assets
    env_file:
      - job.env
    ports:
      - "8004:3333"
  lovs:
    container_name: vsd-server-lovs
    image: vsd-server
    command: sh -c "cd server && node -r dist/apps/lovs/main.js"
    restart: always
    depends_on:
      - main
    volumes:
      - assets:/home/app/assets
    env_file:
      - lovs.env
    ports:
      - "8005:3334"
  mandal:
    container_name: vsd-server-mandal
    image: vsd-server
    command: sh -c "cd server && node -r dist/apps/mandal/main.js"
    restart: always
    depends_on:
      - main
    volumes:
      - assets:/home/app/assets
    env_file:
      - mandal.env
    ports:
      - "8006:3335"
  matrimonial:
    container_name: vsd-server-matrimonial
    image: vsd-server
    command: sh -c "cd server && node -r dist/apps/matrimonial/main.js"
    restart: always
    depends_on:
      - main
    volumes:
      - assets:/home/app/assets
    env_file:
      - matrimonial.env
    ports:
      - "8007:3336"
  news:
    container_name: vsd-server-news
    image: vsd-server
    command: sh -c "cd server && node -r dist/apps/news/main.js"
    restart: always
    depends_on:
      - main
    volumes:
      - assets:/home/app/assets
    env_file:
      - news.env
    ports:
      - "8008:3337"
  temple:
    container_name: vsd-server-temple
    image: vsd-server
    command: sh -c "cd server && node -r dist/apps/temple/main.js"
    restart: always
    depends_on:
      - main
    volumes:
      - assets:/home/app/assets
    env_file:
      - temple.env
    ports:
      - "8009:3338"
  facility:
    container_name: vsd-server-facility
    image: vsd-server
    command: sh -c "cd server && node -r dist/apps/facility/main.js"
    restart: always
    depends_on:
      - main
    volumes:
      - assets:/home/app/assets
    env_file:
      - facility.env
    ports:
      - "8011:3340"
#  vsd-client:
#    container_name: vsd-client
#    image: vsd-client
#    restart: always
#    ports:
#      - "443:443"
#    depends_on:
#      - main
#  vsd-client-admin:
#    container_name: vsd-client-admin
#    image: vsd-client-admin
#    restart: always
#    ports:
#      - "8090:80"
#    depends_on:
#      main:
#        condition: service_healthy
#      event:
#        condition: service_healthy
#      facility:
#        condition: service_healthy
#      family:
#        condition: service_healthy
#      job:
#        condition: service_healthy
#      lovs:
#        condition: service_healthy
#      mandal:
#        condition: service_healthy
#      matrimonial:
#        condition: service_healthy
#      news:
#        condition: service_healthy
#      temple:
#        condition: service_healthy

volumes:
  assets:
    driver: local