-- ------------------------------------------ BUSINESS ---------------------------------------------
INSERT INTO mst_businesses ("businessId", "business", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy") VALUES
  (1, 'Furnishing', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Ad', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Beautiy Parlour', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 'Building Material', TRUE, current_timestamp, 1, current_timestamp, 1),
  (5, 'Chemicals / Minerals', TRUE, current_timestamp, 1, current_timestamp, 1),
  (6, 'Computer Shop', TRUE, current_timestamp, 1, current_timestamp, 1),
  (7, 'Construction Co.', TRUE, current_timestamp, 1, current_timestamp, 1),
  (8, 'Crane', TRUE, current_timestamp, 1, current_timestamp, 1),
  (9, 'Cybercafe', TRUE, current_timestamp, 1, current_timestamp, 1),
  (10, 'Electrical', TRUE, current_timestamp, 1, current_timestamp, 1),
  (11, 'Exporter', TRUE, current_timestamp, 1, current_timestamp, 1),
  (12, 'Fertiliser', TRUE, current_timestamp, 1, current_timestamp, 1),
  (13, 'Fire Equipment', TRUE, current_timestamp, 1, current_timestamp, 1),
  (14, 'Germents', TRUE, current_timestamp, 1, current_timestamp, 1),
  (15, 'Classess', TRUE, current_timestamp, 1, current_timestamp, 1),
  (16, 'Graphics', TRUE, current_timestamp, 1, current_timestamp, 1),
  (17, 'Handicraft', TRUE, current_timestamp, 1, current_timestamp, 1),
  (18, 'Hospital', TRUE, current_timestamp, 1, current_timestamp, 1),
  (19, 'Hotel', TRUE, current_timestamp, 1, current_timestamp, 1),
  (20, 'Industries', TRUE, current_timestamp, 1, current_timestamp, 1),
  (21, 'Marbel', TRUE, current_timestamp, 1, current_timestamp, 1),
  (22, 'Medical', TRUE, current_timestamp, 1, current_timestamp, 1),
  (23, 'Online Trading', TRUE, current_timestamp, 1, current_timestamp, 1),
  (24, 'Organic', TRUE, current_timestamp, 1, current_timestamp, 1),
  (25, 'Paints', TRUE, current_timestamp, 1, current_timestamp, 1),
  (26, 'Pharma', TRUE, current_timestamp, 1, current_timestamp, 1),
  (27, 'Plating', TRUE, current_timestamp, 1, current_timestamp, 1),
  (28, 'Power Equip', TRUE, current_timestamp, 1, current_timestamp, 1),
  (29, 'Painting', TRUE, current_timestamp, 1, current_timestamp, 1),
  (30, 'Readymade Garments', TRUE, current_timestamp, 1, current_timestamp, 1),
  (31, 'Restaurant', TRUE, current_timestamp, 1, current_timestamp, 1),
  (32, 'Security', TRUE, current_timestamp, 1, current_timestamp, 1),
  (33, 'Seqing Machine', TRUE, current_timestamp, 1, current_timestamp, 1),
  (34, 'Spare Parts', TRUE, current_timestamp, 1, current_timestamp, 1),
  (35, 'Steel', TRUE, current_timestamp, 1, current_timestamp, 1),
  (36, 'Studio', TRUE, current_timestamp, 1, current_timestamp, 1),
  (37, 'Tents', TRUE, current_timestamp, 1, current_timestamp, 1),
  (38, 'Timber / Plywood', TRUE, current_timestamp, 1, current_timestamp, 1),
  (39, 'Trading', TRUE, current_timestamp, 1, current_timestamp, 1),
  (40, 'Tubewell', TRUE, current_timestamp, 1, current_timestamp, 1),
  (41, 'Tyres', TRUE, current_timestamp, 1, current_timestamp, 1),
  (42, 'Water Purifier', TRUE, current_timestamp, 1, current_timestamp, 1),
  (43, 'X-Ray Machine', TRUE, current_timestamp, 1, current_timestamp, 1),
  (44, 'Web Design', TRUE, current_timestamp, 1, current_timestamp, 1),
  (45, 'Watches', TRUE, current_timestamp, 1, current_timestamp, 1),
  (46, 'Tution', TRUE, current_timestamp, 1, current_timestamp, 1),
  (47, 'Travel / Transport', TRUE, current_timestamp, 1, current_timestamp, 1),
  (48, 'Tools', TRUE, current_timestamp, 1, current_timestamp, 1),
  (49, 'Textile', TRUE, current_timestamp, 1, current_timestamp, 1),
  (50, 'Sweets', TRUE, current_timestamp, 1, current_timestamp, 1),
  (51, 'Structure Design', TRUE, current_timestamp, 1, current_timestamp, 1),
  (52, 'Spices', TRUE, current_timestamp, 1, current_timestamp, 1),
  (53, 'Solar System', TRUE, current_timestamp, 1, current_timestamp, 1),
  (54, 'Seed', TRUE, current_timestamp, 1, current_timestamp, 1),
  (55, 'Saw Mill', TRUE, current_timestamp, 1, current_timestamp, 1),
  (56, 'Refrigeration', TRUE, current_timestamp, 1, current_timestamp, 1),
  (57, 'Propertyu Dealer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (58, 'Power Press', TRUE, current_timestamp, 1, current_timestamp, 1),
  (59, 'Polymer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (60, 'Placement', TRUE, current_timestamp, 1, current_timestamp, 1),
  (61, 'Petrol Pump', TRUE, current_timestamp, 1, current_timestamp, 1),
  (62, 'Packaging', TRUE, current_timestamp, 1, current_timestamp, 1),
  (63, 'Optics', TRUE, current_timestamp, 1, current_timestamp, 1),
  (64, 'Music', TRUE, current_timestamp, 1, current_timestamp, 1),
  (65, 'Marketing', TRUE, current_timestamp, 1, current_timestamp, 1),
  (66, 'Jewellery', TRUE, current_timestamp, 1, current_timestamp, 1),
  (67, 'Ice-Cream', TRUE, current_timestamp, 1, current_timestamp, 1),
  (68, 'Hostel', TRUE, current_timestamp, 1, current_timestamp, 1),
  (69, 'Hardware', TRUE, current_timestamp, 1, current_timestamp, 1),
  (70, 'Gym Equips', TRUE, current_timestamp, 1, current_timestamp, 1),
  (71, 'Grain Store', TRUE, current_timestamp, 1, current_timestamp, 1),
  (72, 'General Store', TRUE, current_timestamp, 1, current_timestamp, 1),
  (73, 'Furniture', TRUE, current_timestamp, 1, current_timestamp, 1),
  (74, 'Flour Mil', TRUE, current_timestamp, 1, current_timestamp, 1),
  (75, 'Finance', TRUE, current_timestamp, 1, current_timestamp, 1),
  (76, 'Fabrication', TRUE, current_timestamp, 1, current_timestamp, 1),
  (77, 'Electronics', TRUE, current_timestamp, 1, current_timestamp, 1),
  (78, 'Cycle', TRUE, current_timestamp, 1, current_timestamp, 1),
  (79, 'Crockery', TRUE, current_timestamp, 1, current_timestamp, 1),
  (80, 'Courier', TRUE, current_timestamp, 1, current_timestamp, 1),
  (81, 'Cinema / Theater', TRUE, current_timestamp, 1, current_timestamp, 1),
  (82, 'Ceramic', TRUE, current_timestamp, 1, current_timestamp, 1),
  (83, 'Book-Stationery', TRUE, current_timestamp, 1, current_timestamp, 1),
  (84, 'Auto Dealer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (85, 'Shoes', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- SERVICES ---------------------------------------------
INSERT INTO mst_services ("serviceId", "service", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy") VALUES
  (1, 'Software Engineer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Interior Decorator', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Computer Operator', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 'Chartered Accountant', TRUE, current_timestamp, 1, current_timestamp, 1),
  (5, 'Computer Engineer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (6, 'Graphics Designer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (7, 'Hardware Engineer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (8, 'Tax Consultant', TRUE, current_timestamp, 1, current_timestamp, 1),
  (9, 'Actor / Actress', TRUE, current_timestamp, 1, current_timestamp, 1),
  (10, 'Advocate / Lawyer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (11, 'Author / Write', TRUE, current_timestamp, 1, current_timestamp, 1),
  (12, 'Coach / Bodybuilders', TRUE, current_timestamp, 1, current_timestamp, 1),
  (13, 'Agent / Broker', TRUE, current_timestamp, 1, current_timestamp, 1),
  (14, 'Director / Manager', TRUE, current_timestamp, 1, current_timestamp, 1),
  (15, 'Architecture', TRUE, current_timestamp, 1, current_timestamp, 1),
  (16, 'Artist', TRUE, current_timestamp, 1, current_timestamp, 1),
  (17, 'BPO', TRUE, current_timestamp, 1, current_timestamp, 1),
  (18, 'Caterer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (19, 'Designer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (20, 'Doctor', TRUE, current_timestamp, 1, current_timestamp, 1),
  (21, 'Electrictrician', TRUE, current_timestamp, 1, current_timestamp, 1),
  (22, 'Guide', TRUE, current_timestamp, 1, current_timestamp, 1),
  (23, 'Accountant', TRUE, current_timestamp, 1, current_timestamp, 1),
  (24, 'Advisor', TRUE, current_timestamp, 1, current_timestamp, 1),
  (25, 'Arms', TRUE, current_timestamp, 1, current_timestamp, 1),
  (26, 'Astrologer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (27, 'Beautician', TRUE, current_timestamp, 1, current_timestamp, 1),
  (28, 'Carpenter', TRUE, current_timestamp, 1, current_timestamp, 1),
  (29, 'Contractor', TRUE, current_timestamp, 1, current_timestamp, 1),
  (30, 'Driver', TRUE, current_timestamp, 1, current_timestamp, 1),
  (31, 'Mechanic', TRUE, current_timestamp, 1, current_timestamp, 1),
  (32, 'Painter', TRUE, current_timestamp, 1, current_timestamp, 1),
  (33, 'Plumber', TRUE, current_timestamp, 1, current_timestamp, 1),
  (34, 'Salesman', TRUE, current_timestamp, 1, current_timestamp, 1),
  (35, 'Tailor', TRUE, current_timestamp, 1, current_timestamp, 1),
  (36, 'Teacher', TRUE, current_timestamp, 1, current_timestamp, 1),
  (37, 'Musician', TRUE, current_timestamp, 1, current_timestamp, 1),
  (38, 'Photographer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (39, 'Professor', TRUE, current_timestamp, 1, current_timestamp, 1),
  (40, 'Singer', TRUE, current_timestamp, 1, current_timestamp, 1);

SELECT * FROM mst_relationships;
-- ------------------------------------------- GENDER ---------------------------------------------
INSERT INTO mst_genders ("genderId", "gender", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy") VALUES
  (1, 'Male', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Female', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- MARITAL STATUS -------------------------------------
INSERT INTO mst_marital_statuses ("maritalStatusId", "maritalStatus", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Single', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Married', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Divorced', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 'Widowed', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- RELATIONSHIP ---------------------------------------
INSERT INTO mst_relationships ("relationId", "relation", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Father', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Mother', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Brother', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 'Sister', TRUE, current_timestamp, 1, current_timestamp, 1),
  (5, 'Husband', TRUE, current_timestamp, 1, current_timestamp, 1),
  (6, 'Wife', TRUE, current_timestamp, 1, current_timestamp, 1),
  (7, 'Daughter', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- COUNTRY ---------------------------------------------
INSERT INTO mst_countries ("countryId", "country", "countryCode", "active", "createdAt", "updatedAt", "createdBy", "modifiedBy")
VALUES
  (1, 'Afghanistan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (2, 'Albania', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (3, 'Algeria', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (4, 'American Samoa', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (5, 'Andorra', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (6, 'Angola', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (7, 'Anguilla', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (8, 'Antigua and Barbuda', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (9, 'Argentina', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (10, 'Armenia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (11, 'Aruba', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (12, 'Australia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (13, 'Austria', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (14, 'Azerbaijan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (15, 'Bahamas', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (16, 'Bahrain', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (17, 'Bangladesh', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (18, 'Barbados', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (19, 'Belarus', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (20, 'Belgium', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (21, 'Belize', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (22, 'Benin', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (23, 'Bermuda', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (24, 'Bhutan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (25, 'Bolivia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (26, 'Bosnia and Herzegovina', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (27, 'Botswana', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (28, 'Bouvet Island', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (29, 'Brazil', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (30, 'British Indian Ocean territory', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (31, 'Brunei Darussalam', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (32, 'Bulgaria', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (33, 'Burkina Aso', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (34, 'Burundi', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (35, 'Cambodia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (36, 'Cameroon', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (37, 'Canada', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (38, 'Cape Verde', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (39, 'Cayman Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (40, 'Central African Republic', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (41, 'Chad', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (42, 'Chile', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (43, 'China', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (44, 'Christmas Island', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (45, 'Cocos Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (46, 'Colombia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (47, 'Comoros', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (48, 'Congo', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (49, 'Congo, Democratic Republic', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (50, 'Cook Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (51, 'Costa Rica', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (52, 'Croatia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (53, 'Cuba', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (54, 'Cyprus', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (55, 'Czech Republic', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (56, 'Denmark', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (57, 'Djibouti', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (58, 'Dominica', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (59, 'Dominican Republic', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (60, 'Ecuador', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (61, 'Egypt', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (62, 'El Salvador', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (63, 'Equatorial Guinea', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (64, 'Eritrea', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (65, 'Estonia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (66, 'Ethiopia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (67, 'Falkland Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (68, 'Faroe Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (69, 'Fiji', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (70, 'Finland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (71, 'France', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (72, 'French Guiana', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (73, 'French Polynesia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (74, 'French Southern Territories', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (75, 'Gabon', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (76, 'Gambia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (77, 'Georgia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (78, 'Germany', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (79, 'Ghana', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (80, 'Gibraltar', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (81, 'Greece', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (82, 'Greenland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (83, 'Grenada', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (84, 'Guadeloupe', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (85, 'Guam', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (86, 'Guatemala', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (87, 'Guinea', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (88, 'Guinea-Bissau', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (89, 'Guyana', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (90, 'Haiti', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (91, 'Heard and McDonald Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (92, 'Honduras', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (93, 'Hong Kong', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (94, 'Hungary', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (95, 'Iceland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (96, 'India', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (97, 'Indonesia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (98, 'Iran', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (99, 'Iraq', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (100, 'Ireland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (101, 'Israel', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (102, 'Italy', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (103, 'Ivory Coast', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (104, 'Jamaica', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (105, 'Japan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (106, 'Jordan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (107, 'Kazakhstan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (108, 'Kenya', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (109, 'Kiribati', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (110, 'Korea (north)', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (111, 'Korea (south)', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (112, 'Kuwait', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (113, 'Kyrgyzstan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (114, 'Lao Peoples Democratic Republic', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (115, 'Latvia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (116, 'Lebanon', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (117, 'Lesotho', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (118, 'Liberia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (119, 'Libyan Arab Jamahiriya', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (120, 'Liechtenstein', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (121, 'Lithuania', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (122, 'Luxembourg', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (123, 'Macao', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (124, 'Macedonia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (125, 'Madagascar', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (126, 'Malawi', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (127, 'Malaysia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (128, 'Maldives', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (129, 'Mali', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (130, 'Malta', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (131, 'Marshall Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (132, 'Martinique', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (133, 'Mauritania', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (134, 'Mauritius', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (135, 'Mayotte', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (136, 'Mexico', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (137, 'Micronesia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (138, 'Moldova', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (139, 'Monaco', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (140, 'Mongolia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (141, 'Montserrat', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (142, 'Morocco', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (143, 'Mozambique', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (144, 'Myanmar', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (145, 'Namibia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (146, 'Nauru', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (147, 'Nepal', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (148, 'Netherlands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (149, 'Netherlands Antilles', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (150, 'New Caledonia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (151, 'New Zealand', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (152, 'Nicaragua', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (153, 'Niger', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (154, 'Nigeria', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (155, 'Niue', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (156, 'Norfolk Island', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (157, 'Northern Mariana Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (158, 'Norway', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (159, 'Oman', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (160, 'Pakistan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (161, 'Palau', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (162, 'Palestinian Territories', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (163, 'Panama', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (164, 'Papua New Guinea', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (165, 'Paraguay', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (166, 'Peru', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (167, 'Philippines', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (168, 'Pitcairn', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (169, 'Poland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (170, 'Portugal', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (171, 'Puerto Rico', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (172, 'Qatar', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (173, 'Reunion', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (174, 'Romania', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (175, 'Russian Federation', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (176, 'Rwanda', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (177, 'Saint Helena', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (178, 'Saint Kitts and Nevis', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (179, 'Saint Lucia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (180, 'Saint Pierre and Miquelon', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (181, 'Saint Vincent and the Grenadines', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (182, 'Samoa', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (183, 'San Marino', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (184, 'Sao Tome and Principe', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (185, 'Saudi Arabia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (186, 'Senegal', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (187, 'Serbia and Montenegro', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (188, 'Seychelles', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (189, 'Sierra Leone', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (190, 'Singapore', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (191, 'Slovakia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (192, 'Slovenia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (193, 'Solomon Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (194, 'Somalia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (195, 'South Africa', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (196, 'South Georgia and the South Sandwich Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (197, 'Spain', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (198, 'Sri Lanka', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (199, 'Sudan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (200, 'Suriname', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (201, 'Svalbard and Jan Mayen Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (202, 'Swaziland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (203, 'Sweden', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (204, 'Switzerland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (205, 'Syria', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (206, 'Taiwan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (207, 'Tajikistan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (208, 'Tanzania', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (209, 'Thailand', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (210, 'Togo', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (211, 'Tokelau', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (212, 'Tonga', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (213, 'Trinidad and Tobago', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (214, 'Tunisia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (215, 'Turkey', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (216, 'Turkmenistan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (217, 'Turks and Caicos Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (218, 'Tuvalu', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (219, 'Uganda', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (220, 'Ukraine', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (221, 'United Arab Emirates', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (222, 'United Kingdom', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (223, 'United States', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (224, 'Uruguay', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (225, 'Uzbekistan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (226, 'Vanuatu', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (227, 'Venezuela', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (228, 'Vietnam', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (229, 'Virgin Islands (British)', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (230, 'Virgin Islands (US)', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (231, 'Wallis and Futuna Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (232, 'Western Sahara', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (233, 'Yemen', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (234, 'Zambia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1),
  (235, 'Zimbabwe', NULL, TRUE, current_timestamp, current_timestamp, 1, 1);

-- ------------------------------------------- STATE ---------------------------------------------
INSERT INTO mst_states ("stateId", "countryId", "state", "stateCode", "active", "createdAt", "updatedAt", "createdBy", "modifiedBy")
VALUES
  (1, 96, 'Jammu & Kashmir', 1, TRUE, current_timestamp, current_timestamp, 1, 1),
  (2, 96, 'Himachal Pradesh', 2, TRUE, current_timestamp, current_timestamp, 1, 1),
  (3, 96, 'Punjab', 3, TRUE, current_timestamp, current_timestamp, 1, 1),
  (4, 96, 'Chandigarh', 4, TRUE, current_timestamp, current_timestamp, 1, 1),
  (5, 96, 'Uttarakhand', 5, TRUE, current_timestamp, current_timestamp, 1, 1),
  (6, 96, 'Haryana', 6, TRUE, current_timestamp, current_timestamp, 1, 1),
  (7, 96, 'Delhi', 7, TRUE, current_timestamp, current_timestamp, 1, 1),
  (8, 96, 'Rajasthan', 8, TRUE, current_timestamp, current_timestamp, 1, 1),
  (9, 96, 'Uttar Pradesh', 9, TRUE, current_timestamp, current_timestamp, 1, 1),
  (10, 96, 'Bihar', 10, TRUE, current_timestamp, current_timestamp, 1, 1),
  (11, 96, 'Sikkim', 11, TRUE, current_timestamp, current_timestamp, 1, 1),
  (12, 96, 'Arunachal Pradesh', 12, TRUE, current_timestamp, current_timestamp, 1, 1),
  (13, 96, 'Nagaland', 13, TRUE, current_timestamp, current_timestamp, 1, 1),
  (14, 96, 'Manipur', 14, TRUE, current_timestamp, current_timestamp, 1, 1),
  (15, 96, 'Mizoram', 15, TRUE, current_timestamp, current_timestamp, 1, 1),
  (16, 96, 'Tripura', 16, TRUE, current_timestamp, current_timestamp, 1, 1),
  (17, 96, 'Meghalaya', 17, TRUE, current_timestamp, current_timestamp, 1, 1),
  (18, 96, 'Assam', 18, TRUE, current_timestamp, current_timestamp, 1, 1),
  (19, 96, 'West Bengal', 19, TRUE, current_timestamp, current_timestamp, 1, 1),
  (20, 96, 'Jharkhand', 20, TRUE, current_timestamp, current_timestamp, 1, 1),
  (21, 96, 'Orissa', 21, TRUE, current_timestamp, current_timestamp, 1, 1),
  (22, 96, 'Chhattisgarh', 22, TRUE, current_timestamp, current_timestamp, 1, 1),
  (23, 96, 'Madhya Pradesh', 23, TRUE, current_timestamp, current_timestamp, 1, 1),
  (24, 96, 'Gujarat', 24, TRUE, current_timestamp, current_timestamp, 1, 1),
  (25, 96, 'Daman & Diu', 25, TRUE, current_timestamp, current_timestamp, 1, 1),
  (26, 96, 'Dadra & Nagar Haveli', 26, TRUE, current_timestamp, current_timestamp, 1, 1),
  (27, 96, 'Maharashtra', 27, TRUE, current_timestamp, current_timestamp, 1, 1),
  (28, 96, 'Andhra Pradesh', 28, TRUE, current_timestamp, current_timestamp, 1, 1),
  (29, 96, 'Karnataka', 29, TRUE, current_timestamp, current_timestamp, 1, 1),
  (30, 96, 'Goa', 30, TRUE, current_timestamp, current_timestamp, 1, 1),
  (31, 96, 'Lakshadweep', 31, TRUE, current_timestamp, current_timestamp, 1, 1),
  (32, 96, 'Kerala', 32, TRUE, current_timestamp, current_timestamp, 1, 1),
  (33, 96, 'Tamil Nadu', 33, TRUE, current_timestamp, current_timestamp, 1, 1),
  (34, 96, 'Puducherry', 34, TRUE, current_timestamp, current_timestamp, 1, 1),
  (35, 96, 'Andaman & Nicobar Islands', 35, TRUE, current_timestamp, current_timestamp, 1, 1),
  (36, 96, 'Telengana', 36, TRUE, current_timestamp, current_timestamp, 1, 1),
  (37, 96, 'Andrapradesh', 37, TRUE, current_timestamp, current_timestamp, 1, 1);

-- ------------------------------------------- DISTRICT ---------------------------------------------
INSERT INTO mst_districts ("districtId", "stateId", "district", "active", "createdAt", "updatedAt", "createdBy", "modifiedBy")
VALUES
  (1, 8, 'Jalore', TRUE, current_timestamp, current_timestamp, 1, 1),
  (2, 8, 'Sirohi', TRUE, current_timestamp, current_timestamp, 1, 1),
  (3, 8, '3', TRUE, current_timestamp, current_timestamp, 1, 1),
  (4, 8, 'Pali', TRUE, current_timestamp, current_timestamp, 1, 1),
  (5, 8, 'Rajsamand', TRUE, current_timestamp, current_timestamp, 1, 1),
  (6, 8, 'banaskantha', TRUE, current_timestamp, current_timestamp, 1, 1),
  (7, 8, 'Dhara', TRUE, current_timestamp, current_timestamp, 1, 1);

INSERT INTO mst_districts ("districtId", "stateId", "district", "active", "createdAt", "updatedAt", "createdBy", "modifiedBy")
VALUES
  (11, 27, 'Mumbai', TRUE, current_timestamp, current_timestamp, 1, 1),
  (12, 27, 'Thane', TRUE, current_timestamp, current_timestamp, 1, 1);

INSERT INTO mst_districts ("districtId", "stateId", "district", "active", "createdAt", "updatedAt", "createdBy", "modifiedBy")
VALUES
  (13, 23, 'Ratlam', TRUE, current_timestamp, current_timestamp, 1, 1),
  (14, 24, 'Dantivada', TRUE, current_timestamp, current_timestamp, 1, 1),
  (15, 24, 'Ahmedabad', TRUE, current_timestamp, current_timestamp, 1, 1);

-- ------------------------------------------- CITY VILLAGE ---------------------------------------------
INSERT INTO mst_city_villages ("cityVillageId", "typeId", "cityVillage", "districtId", "pinCode", "stdCode", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 1, 'Agawari', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 1, 'Ajari', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 1, 'Andor', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 1, 'Amirama', '3', '312401', '1473', TRUE, current_timestamp, 1, current_timestamp, 1),
  (5, 1, 'Asava', 2, '307511', '2975', TRUE, current_timestamp, 1, current_timestamp, 1),
  (6, 1, 'Aipura', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (7, 1, 'Aakorapadar', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (8, 1, 'Aana', 4, '306703', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (9, 1, 'Aalpa', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (10, 1, 'Ahore', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (11, 1, 'Isali', 4, '306026', '2935', TRUE, current_timestamp, 1, current_timestamp, 1),
  (12, 1, 'Uthnam', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (13, 1, 'Umedpur', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (14, 1, 'Karavnaa', 4, '307006', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (15, 1, 'Kalapura', 1, '307515', '2990', TRUE, current_timestamp, 1, current_timestamp, 1),
  (16, 1, 'Kawarada', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (17, 1, 'Kanpura', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (18, 1, 'Kamba', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (19, 1, 'Kalndri', 2, '307802', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (20, 1, 'Kasindra', 2, '307023', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (21, 1, 'Kirva', 4, '306422', '2932', TRUE, current_timestamp, 1, current_timestamp, 1),
  (22, 1, 'Kesua', 2, '307512', '2975', TRUE, current_timestamp, 1, current_timestamp, 1),
  (23, 1, 'Kelashnagar', 2, '307801', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (24, 1, 'Kota (Baliyan)', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (25, 1, 'Kotdi', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (26, 1, 'Korta', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (27, 1, 'Kolpura', 4, '306022', '2935', TRUE, current_timestamp, 1, current_timestamp, 1),
  (28, 1, 'Koliwada', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (29, 1, 'Koselaw', 4, '306710', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (30, 1, 'Kurshnajhang (Meda)', 2, '307001', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (31, 1, 'Kandra', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (32, 1, 'Kimada', 4, '306710', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (33, 1, 'Kimel', 4, '306115', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (34, 1, 'Kiwada', 4, '306502', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (35, 1, 'Kiwandi', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (36, 1, 'Kudala', 4, '306116', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (37, 1, 'Gangawa', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (38, 1, 'Galthani', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (39, 1, 'Girali', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (40, 1, 'Guda Balota', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (41, 1, 'Guda Maharamji', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (42, 1, 'Godan', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (43, 1, 'Gol', 2, '307001', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (44, 1, 'Ghanerao', 4, '306704', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (45, 1, 'Cherli', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (46, 1, 'Chawarcha', 1, '343001', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (47, 1, 'Chanchodi', 4, '306115', '2932', TRUE, current_timestamp, 1, current_timestamp, 1),
  (48, 1, 'Chanod', 4, '306602', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (49, 1, 'Chandana', 1, '343024', '2973', TRUE, current_timestamp, 1, current_timestamp, 1),
  (50, 1, 'Chaudhari', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (51, 1, 'Chamundari', 4, '306504', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (52, 1, 'Charbhuja', '5', '313333', '2954', TRUE, current_timestamp, 1, current_timestamp, 1),
  (53, 1, 'Chiparwada', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (54, 1, 'Chibagoaw', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (55, 1, 'Janapur', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (56, 1, 'Jhakhoda', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (57, 1, 'Jhato Ka Guda', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (58, 1, 'Javal', 2, '307801', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (59, 1, 'Junna', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (60, 1, 'Jela', 2, '307802', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (61, 1, 'Joghpur', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (62, 1, 'Joda (Agawari)', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (63, 1, 'Jhadholi', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (64, 1, 'Dongurli', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (65, 1, 'Dhalop', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (66, 1, 'Takatghad', 4, '306912', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (67, 1, 'Tavri', 2, '307802', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (68, 1, 'Thavla', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (69, 1, 'Thumba', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (70, 1, 'Dantigoan', 7, '454116', '7296', TRUE, current_timestamp, 1, current_timestamp, 1),
  (71, 1, 'Dayalpura', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (72, 1, 'Degaon', 1, '343025', '2973', TRUE, current_timestamp, 1, current_timestamp, 1),
  (73, 1, 'Dujana', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (74, 1, 'Dudni', 4, '306504', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (75, 1, 'Deldar', 2, '307801', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (76, 1, 'Devli', 4, '306024', '2935', TRUE, current_timestamp, 1, current_timestamp, 1),
  (77, 1, 'Desuri', 4, '306703', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (78, 1, 'Dolpura', 2, '307026', '2975', TRUE, current_timestamp, 1, current_timestamp, 1),
  (79, 1, 'Ghani', 4, '306116', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (80, 1, 'Naya Sanwada', 2, '307021', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (81, 1, 'Nadol', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (82, 1, 'Nana', 4, '306504', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (83, 1, 'Narlai', 4, '306703', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (84, 1, 'Navdiya', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (85, 1, 'Nipal', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (86, 1, 'Nouvi', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (87, 1, 'Parakhiya', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (88, 1, 'Patava', 4, '306707', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (89, 1, 'Padarli', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (90, 1, 'Paldi ', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (91, 1, 'Pavtha', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (92, 1, 'Pava', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (93, 1, 'Pichava', 4, '306115', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (94, 1, 'Pindharadha', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (95, 1, 'Pindhiya', 4, '306115', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (96, 1, 'Peshua', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (97, 1, 'Pomava', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (98, 1, 'Posaliya', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (99, 1, 'Fatapura', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (100, 1, 'Falna ', 4, '306116', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (101, 1, 'Bhadgoan', 2, '307027', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (102, 1, 'Bada ', 4, '306707', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (103, 1, 'Barod', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (104, 1, 'Basant', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (105, 1, 'Basantgadh', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (106, 1, 'Bokhali', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (107, 1, 'Bogdhi', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (108, 1, 'Bagra', 1, '343025', '2973', TRUE, current_timestamp, 1, current_timestamp, 1),
  (109, 1, 'Botha', 4, '306503', '2935', TRUE, current_timestamp, 1, current_timestamp, 1),
  (110, 1, 'Badanwari', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (111, 1, 'Babogoan', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (112, 1, 'Bamnera', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (113, 1, 'Barva', 4, '306706', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (114, 1, 'Barewada', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (115, 1, 'Bali', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (116, 1, 'Bhichawadi', 1, '343001', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (117, 1, 'Bhijhowa', 4, '306601', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (118, 1, 'Birami', 4, '306115', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (119, 1, 'Bijapur', 4, '306707', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (120, 1, 'Budtar', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (121, 1, 'Boya', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (122, 1, 'Bhandar', 4, '306504', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (123, 1, 'Barundra', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (124, 1, 'Bathund', 4, '306707', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (125, 1, 'Bhadras', 4, '306702', '29934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (126, 1, 'Bhavri', 2, '307041', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (127, 1, 'Bhitwada', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (128, 1, 'Bhiitgaon', 2, '307801', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (129, 1, 'Bhooti', 1, '307030', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (130, 1, 'Bhetala', 1, '343024', '2973', TRUE, current_timestamp, 1, current_timestamp, 1),
  (131, 1, 'Bhev', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (132, 1, 'Bhenswara', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (133, 1, 'Mandwariya', 2, '307801', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (134, 1, 'Mandal', 4, '306115', '2932', TRUE, current_timestamp, 1, current_timestamp, 1),
  (135, 1, 'Madni', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (136, 1, 'Mada', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (137, 1, 'Madhopura', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (138, 1, 'Malpura', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (139, 1, 'Malari', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (140, 1, 'Mithdi', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (141, 1, 'Mundara', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (142, 1, 'Mokapura', 4, '303115', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (143, 1, 'Morkha', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (144, 1, 'Morli', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (145, 1, 'Morana', 5, '313333', '2954', TRUE, current_timestamp, 1, current_timestamp, 1),
  (146, 1, 'Monka', 1, '343025', '2973', TRUE, current_timestamp, 1, current_timestamp, 1),
  (147, 1, 'Rasiyavash', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (148, 1, 'Rani ', 4, '306115', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (149, 1, 'Rani ', 4, '306115', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (150, 1, 'Ramnagar', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (151, 1, 'Rodhla', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (152, 1, 'Rovada', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (153, 1, 'Rohidha', 2, '307024', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (154, 1, 'Lalrai', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (155, 1, 'Lunawa', 4, '306706', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (156, 1, 'Lothiwada', 2, '307801', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (157, 1, 'Vandar', 4, '306502', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (158, 1, 'Varkana', 4, '306601', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (159, 1, 'Kaldara', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (160, 1, 'Vagshen', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (161, 1, 'Vasa', 2, '307024', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (162, 1, 'Vikanwas', 1, '307515', '2990', TRUE, current_timestamp, 1, current_timestamp, 1),
  (163, 1, 'Vingrla', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (164, 1, 'Verampura', 4, '306504', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (165, 1, 'Verwada', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (166, 1, 'Vadiya', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (167, 1, 'Valengari', 2, '307001', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (168, 1, 'Velar', 4, '306504', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (169, 1, 'Sankhwali', 1, '307029', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (170, 1, 'Shivganj', 2, '307027', '2976', TRUE, current_timestamp, 1, current_timestamp, 1),
  (171, 1, 'Shiwatlav', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (172, 1, 'Sladriya', 2, '307027', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (173, 1, 'Savli', 2, '307801', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (174, 1, 'Sanderao', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (175, 1, 'Shanthu', 1, '343026', '2973', TRUE, current_timestamp, 1, current_timestamp, 1),
  (176, 1, 'Sadar', 4, '306706', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (177, 1, 'Sadri', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (178, 1, 'Samuja', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (179, 1, 'Sarlriya', 4, '306117', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (180, 1, 'Sindheru', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (181, 1, 'Siana', 1, '343024', '2973', TRUE, current_timestamp, 1, current_timestamp, 1),
  (182, 1, 'Sirohi', 2, '307001', '2972', TRUE, current_timestamp, 1, current_timestamp, 1),
  (183, 1, 'Sirohi ', 2, '307021', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (184, 1, 'Sivera', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1),
  (185, 1, 'Sutharo ', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1),
  (186, 1, 'Sumerpur', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (187, 1, 'Sdriya', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (188, 1, 'Sewadi', 4, '306707', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (189, 1, 'Sokada', 4, '306706', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (190, 1, 'Saysli', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (191, 1, 'Sonpura', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (192, 1, 'Sri ', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1),
  (193, 1, 'Harji', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (194, 1, 'Hariyali', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1),
  (195, 1, 'Jetawada', 2, '307513', '2975', TRUE, current_timestamp, 1, current_timestamp, 1),
  (196, 1, 'Takathadh', 4, '306912', '2933', TRUE, current_timestamp, 1, current_timestamp, 1),
  (197, 1, 'Pounthawada', 6, '385546', '2748', TRUE, current_timestamp, 1, current_timestamp, 1),
  (198, 1, 'Dhaniyawada', 6, '385505', '2748', TRUE, current_timestamp, 1, current_timestamp, 1),
  (199, 1, 'Bhanaotra', 6, '385545', '2748', TRUE, current_timestamp, 1, current_timestamp, 1),
  (200, 1, 'Mandar', 2, '307513', '2975', TRUE, current_timestamp, 1, current_timestamp, 1),
  (201, 1, 'Maalpura', 2, '307513', '2975', TRUE, current_timestamp, 1, current_timestamp, 1),
  (202, 1, 'Raniwara', 1, '343040', '2990', TRUE, current_timestamp, 1, current_timestamp, 1),
  (203, 1, 'Revdar', 2, '307514', '2975', TRUE, current_timestamp, 1, current_timestamp, 1),
  (204, 1, 'Vadgaon ', 1, '343048', '2990', TRUE, current_timestamp, 1, current_timestamp, 1);

INSERT INTO mst_city_villages ("cityVillageId", "typeId", "cityVillage", "districtId", "pinCode", "stdCode", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (205, 2, 'Churchgate', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (206, 2, 'Marine Lines', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (207, 2, 'Charni Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (208, 2, 'Grant Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (209, 2, 'Mumbai Central', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (210, 2, 'Maha Laxmi', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (211, 2, 'Lower Parel', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (212, 2, 'Elphinstone Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (213, 2, 'Dadar', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (214, 2, 'Matunga Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (215, 2, 'Mahim Junction', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (216, 2, 'Bandra', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (217, 2, 'Khar Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (218, 2, 'Santacruz', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (219, 2, 'Vile Parle', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (220, 2, 'Andheri', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (221, 2, 'Jogeshwari', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (222, 2, 'Goregaon', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (223, 2, 'Malad', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (224, 2, 'Kandivili', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (225, 2, 'Borivali', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (226, 2, 'Dahisar', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (227, 2, 'Mira Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (228, 2, 'Bhayander', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (229, 2, 'Nalgaon', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (230, 2, 'Vasai Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (231, 2, 'Nala Sopara', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (232, 2, 'Virar', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (233, 2, 'Vaitarna', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (234, 2, 'Saphale', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (235, 2, 'Kelve Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (236, 2, 'Palghar', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (237, 2, 'Umroli', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (238, 2, 'Boisar', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (239, 2, 'Vangaon', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (240, 2, 'Dahanu Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (241, 2, 'Thane', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (242, 2, 'Dighe', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (243, 2, 'Airoli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (244, 2, 'Rabale', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (245, 2, 'Ghansoli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (246, 2, 'Kopar ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (247, 2, 'Turbhe', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (248, 2, 'Sanpada', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (249, 2, 'Vashi', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (250, 2, 'Jui ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (251, 2, 'Nerul', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (252, 2, 'Seawoods ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (253, 2, 'Belapur ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (254, 2, 'Kharghar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (255, 2, 'Mansarovar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (256, 2, 'Khandeshwar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (257, 2, 'Panvel ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (258, 2, 'CST', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (259, 2, 'Masjid', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (260, 2, 'Sandhurt ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (261, 2, 'Docyard ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (262, 2, 'Reay ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (263, 2, 'Cotton ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (264, 2, 'Sewri', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (265, 2, 'Vadala ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (266, 2, 'King ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (267, 2, 'Guru ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (268, 2, 'Chunabhatti', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (269, 2, 'Kurla ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (270, 2, 'Tilaknagar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (271, 2, 'Chembur', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (272, 2, 'Govandi', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (273, 2, 'Mankhurd', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (274, 2, 'Vashi', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (275, 2, 'Vasai ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (276, 2, 'Juchandr', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (277, 2, 'Kaman ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (278, 2, 'Kharbav', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (279, 2, 'Bhiwandi ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (280, 2, 'Kopar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (281, 2, 'Diva ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (282, 2, 'Mumbai ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (283, 2, 'Masjid', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (284, 2, 'Sandhurst ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (285, 2, 'Byculla ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (286, 2, 'Chinchpokli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (287, 2, 'Currey ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (288, 2, 'Parel', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (289, 2, 'Dadar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (290, 2, 'Matunga', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (291, 2, 'Sion', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (292, 2, 'Kurla', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (293, 2, 'Vidyavihar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (294, 2, 'Ghatkopar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (295, 2, 'Vikhroli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (296, 2, 'Kanjur ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (297, 2, 'Bhandup', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (298, 2, 'Nahur', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (299, 2, 'Mulund', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (300, 2, 'Thane', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (301, 2, 'Kalva', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (302, 2, 'Mumbra', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (303, 2, 'Diva ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (304, 2, 'Kopar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (305, 2, 'Dombivali', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (306, 2, 'Thakurli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (307, 2, 'Kalyan ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (308, 2, 'Shahad', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (309, 2, 'Ambivali', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (310, 2, 'Titwala', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (311, 2, 'Khadavali', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (312, 2, 'Vasind', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (313, 2, 'Asangaon', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (314, 2, 'Atgaon', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (315, 2, 'Thansit', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (316, 2, 'Khardi', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (317, 2, 'Oombermali', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (318, 2, 'Kasara', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (319, 2, 'Vithalwadi', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (320, 2, 'Ulhasnagar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (321, 2, 'Ambernath', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (322, 2, 'Badlapur', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (323, 2, 'Vangani', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (324, 2, 'Shelu', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (325, 2, 'Nerul', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (326, 2, 'Bhipuri ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (327, 2, 'Karjat', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (328, 2, 'Palasdari', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (329, 2, 'Kelavli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (330, 2, 'Dolavli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (331, 2, 'Lowjee', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (332, 2, 'Khopoli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1);

INSERT INTO mst_city_villages ("cityVillageId", "typeId", "cityVillage", "districtId", "pinCode",
                               "stdCode", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (333, 1, 'Ringnod', 13, '457336', NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (334, 1, 'Panthawada', 14, '385545', NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (335, 1, 'Ahmedabad', 15, '380019', NULL, TRUE, current_timestamp, 1, current_timestamp, 1);


-- ------------------------------------------- POST ---------------------------------------------
INSERT INTO mst_posts ("postId", "post", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Guardian', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Chairman', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Vice Chairman', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 'General Secretary', TRUE, current_timestamp, 1, current_timestamp, 1),
  (5, 'Treasurer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (6, 'Joint Treasurer', TRUE, current_timestamp, 1, current_timestamp, 1),
  (7, 'Secretary', TRUE, current_timestamp, 1, current_timestamp, 1),
  (8, 'Joint Secretary', TRUE, current_timestamp, 1, current_timestamp, 1),
  (9, 'Management', TRUE, current_timestamp, 1, current_timestamp, 1),
  (10, 'Advisor', TRUE, current_timestamp, 1, current_timestamp, 1),
  (11, 'Accountants', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- ADDRESS TYPE ---------------------------------------------
INSERT INTO mst_address_types ("addressTypeId", "addressType", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Permanent Address', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Communication Address', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Office Address', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- CONTACT NUMBER TYPE ---------------------------------------------
INSERT INTO mst_contact_types ("contactTypeId", "contactType", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Mobile Number', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Alternate Number', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Landline Number', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 'Office Number', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Religion ---------------------------------------------
INSERT INTO mst_religions ("religionId", "religion", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Hindu', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Gotra ---------------------------------------------
INSERT INTO mst_gotras ("gotraId", "gotra", "active", "createdAt", "createdBy",  "updatedAt", "modifiedBy")
VALUES
  (1, 'Parihar', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Chouhan', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Solanki', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 'Parmar', TRUE, current_timestamp, 1, current_timestamp, 1),
  (5, 'Tripasta', TRUE, current_timestamp, 1, current_timestamp, 1),
  (6, 'Rathod', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Addiction ---------------------------------------------
INSERT INTO mst_addictions ("addictionId", "addiction", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Tobacco', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Alcohol', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Smoking', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Caste ---------------------------------------------
INSERT INTO mst_castes ("casteId", "caste", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Suthar', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Request Status ---------------------------------------------
INSERT INTO mst_matrimonial_requested_statuses ("requestedStatusId", "requestedStatus", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Accepted', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Rejected', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Ignore', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Matrimonial Status ---------------------------------------------
INSERT INTO mst_matrimonial_statuses ("matrimonialStatusId", "matrimonialStatus", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Waiting For Approval', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Approved', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Rejected', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 'Closed', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Education Degree ---------------------------------------------
INSERT INTO mst_education_degrees ("educationDegreeId", "educationDegree","active" ,"createdAt","createdBy","updatedAt","modifiedBy")
VALUES
  (1, 'No Education', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Below 5th Class', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, '8th Pass', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, '10th (SSC) Pass', TRUE, current_timestamp, 1, current_timestamp, 1),
  (5, '12th (HSC) Pass', TRUE, current_timestamp, 1, current_timestamp, 1),
  (6, 'B. Com.', TRUE, current_timestamp, 1, current_timestamp, 1),
  (7, 'B. E.', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Media Src ---------------------------------------------
INSERT INTO mst_media_srcs ("mediaSrcId", "mediaSrc", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Server', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Media Type ---------------------------------------------
INSERT INTO mst_media_types ("mediaTypeId", "mediaType", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Image', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Video', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Raasi ---------------------------------------------
INSERT INTO mst_raasis ("raasiId", "raasi", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Mesh (Aries)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Varishabha (Taurus)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Mithuna (Gemini)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 'Karka (Cancer)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (5, 'Simha (Leo)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (6, 'Kanya (Virgo)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (7, 'Tula (Libra)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (8, 'Vrischika (Scorpio)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (9, 'Dhanur (Sagittarious)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (10, 'Makara (Capricorn)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (11, 'Kumbha (Aquarius)', TRUE, current_timestamp, 1, current_timestamp, 1),
  (12, 'Meena (Pisces)', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Table ---------------------------------------------
INSERT INTO mst_tables VALUES (1, 'txn_events', NOW(), NOW());
INSERT INTO mst_tables VALUES (2, 'txn_familys', NOW(), NOW());
INSERT INTO mst_tables VALUES (3, 'txn_temples', NOW(), NOW());
INSERT INTO mst_tables VALUES (4, 'txn_mandals', NOW(), NOW());
INSERT INTO mst_tables VALUES (5, 'mst_admin_users', NOW(), NOW());

-- ------------------------------------------- TEMPLE ---------------------------------------------

INSERT INTO txn_addresses ("addressId", "tableId", "pkOfTable", "addressTypeId", "address",
                           "pinCode", "cityVillageId", "latitude", "longitude", "active",
                           "createdIp", "modifiedIp", "createdAt", "updatedAt","districtId","stateId", "countryId" )
VALUES
  (1, 3, 1, 3, 'Vishwakarma mandir', '306706',113, 25.1264051, 73.3157686,TRUE, ':0', ':0', now(), now(), 1, 8, 96),
(2, 3, 2, 3, 'Ringnod', '457336',333, 23.7375145, 75.1755614,TRUE, ':0', ':0', now(), now(), 2, 8, 96),
(3, 3, 3, 3, 'Sutharo Ka Vas', '343001',193,25.2901106,72.8548346,TRUE, ':0', ':0', now(), now(), 1, 8, 96),
(4, 3, 4, 3, 'Sutharon Ka Vas', '307029',10,25.3688712, 72.777957,TRUE, ':0', ':0', now(), now(), 4, 8, 96),
(5, 3, 5, 3, 'Athmanavas', '343025',108,25.195514,72.5850005,TRUE, ':0', ':0', now(), now(), 2, 8, 96),
(8, 3, 8, 3, 'Siana- Sirohi Main Road, Varada', '307801',165,25.0044297,72.4165222,TRUE, ':0', ':0', now(), now(), 2, 8, 96),
(9, 3, 9, 3, 'Sutharo Ka Vas, New Nehru Nagar', '307027',170,25.13688,73.0676513,TRUE, ':0', ':0', now(), now(), 2, 8, 96),
(12, 3, 12, 3, 'Dantrai', '307512',22,24.7123047,72.5184889,TRUE, ':0', ':0', now(), now(), 1, 8, 96),
(13, 3, 13, 3, 'Suthar Vaas St, Vedhaynath Colony', '307001',182,24.8829412,72.8615207,TRUE, ':0', ':0', now(), now(), 13, 23, 96),
(14, 3, 14, 3, 'Panthawada', '385545',334,24.4955766,72.2991274,TRUE, ':0', ':0', now(), now(), 14, 24, 96),
(15, 3, 15, 3, 'Ram Nagar, Sabarmati', '380019',335, 23.0930829,72.5822966,TRUE, ':0', ':0', now(), now(), 15, 25, 96);

INSERT INTO mst_temples ("templeId", "addressId", "templeName", "imagePath", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 1, 'बारवा', null, TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 2, 'रिगनोंगद', null, TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 3, 'हरजी', null, TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 4, 'आहोर', null, TRUE, current_timestamp, 1, current_timestamp, 1),
  (5, 5, 'बागरा', NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (8, 8, 'सिरोही', NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (9, 9, 'शिंवगंज', NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (12, 12, 'दांतराई', NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (13, 13, 'पामेरा', NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (14, 14, 'पांथावाडा', NULL, TRUE, current_timestamp, 1, current_timestamp, 1),
  (15, 15, 'साबरमती', NULL, TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- MANDAL ---------------------------------------------
INSERT INTO txn_addresses ("addressId", "tableId", "pkOfTable", "addressTypeId", "address",
                           "pinCode", "cityVillageId", "latitude", "longitude", "active",
                           "createdIp", "modifiedIp", "createdAt", "updatedAt", "districtId","stateId", "countryId")
VALUES
  (16, 4, 1, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96),
  (17, 4, 2, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96),
  (18, 4, 3, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96),
  (19, 4, 4, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96),
  (20, 4, 5, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96),
  (21, 4, 6, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96),
  (22, 4, 7, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96),
  (23, 4, 8, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96),
  (24, 4, 9, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96),
  (25, 4, 10, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96),
  (26, 4, 11, 3, 'Bhayendar', '401104',228,null, null,TRUE, ':0', ':0', now(), now(), 11, 27, 96);

INSERT INTO mst_mandals ("mandalId", "mandal", "addressId", "active", "createdAt", "createdBy", "updatedAt", "modifiedBy")
VALUES
  (1, 'Shree Vishwakarma Vansh Suthar Charitable Trust', 16,TRUE, current_timestamp, 1, current_timestamp, 1),
  (2, 'Shree Vishwakarma Vansh Suthar Samaj Charitable Trust', 17,TRUE, current_timestamp, 1, current_timestamp, 1),
  (3, 'Shree Vishwakarma Vansh Suthar Samaj', 18,TRUE, current_timestamp, 1, current_timestamp, 1),
  (4, 'Shree Vishwakarma Vansh Suthar Nav Yuvak Mandal', 19,TRUE, current_timestamp, 1, current_timestamp, 1),
  (5, 'Shree Vishwakarma Vansh Suthar Nav Yuvak Mandal', 20,TRUE, current_timestamp, 1, current_timestamp, 1),
  (6, 'Shree Vishwakarma Vansh Suthar Mandal', 21,TRUE, current_timestamp, 1, current_timestamp, 1),
  (7, 'Shree Vishwakarma Vansh Suthar Nav Yuvak Mandal', 22,TRUE, current_timestamp, 1, current_timestamp, 1),
  (8, 'Shree Vishwakarma Vansh Suthar Mandal', 23,TRUE, current_timestamp, 1, current_timestamp, 1),
  (9, 'Shree Vishwakarma Vansh Suthar Mandal', 24,TRUE, current_timestamp, 1, current_timestamp, 1),
  (10, 'Shree Vishwakarma Vansh Suthar Youth Federation', 25,TRUE, current_timestamp, 1, current_timestamp, 1),
  (11, 'Shree Vishwakarma Vansh Suthar Ganesh Utsav Mandal', 26,TRUE, current_timestamp, 1, current_timestamp, 1);
