-- ------------------------------------------ BUSINESS ---------------------------------------------
insert into mst_business
(business_id, business, active, created_at, created_by, updated_at, modified_by)
VALUES (1, 'Furnishing', TRUE, current_timestamp, 1, current_timestamp, 1),
       (2, 'Ad', TRUE, current_timestamp, 1, current_timestamp, 1),
       (3, 'Beautiy Parlour', TRUE, current_timestamp, 1, current_timestamp, 1),
       (4, 'Building Material', TRUE, current_timestamp, 1, current_timestamp, 1),
       (5, 'Chemicals / Minerals', TRUE, current_timestamp, 1, current_timestamp, 1),
       (6, 'Computer Shop', TRUE, current_timestamp, 1, current_timestamp, 1),
       (7, 'Construction Co.', TRUE, current_timestamp, 1, current_timestamp, 1),
       (8, 'Crane', TRUE, current_timestamp, 1, current_timestamp, 1),
       (9, 'Cybercafe', TRUE, current_timestamp, 1, current_timestamp, 1),
       (10, 'Electrical', TRUE, current_timestamp, 1, current_timestamp, 1),
       (11, 'Exporter', TRUE, current_timestamp, 1, current_timestamp, 1),
       (12, 'Fertiliser', TRUE, current_timestamp, 1, current_timestamp, 1),
       (13, 'Fire Equipment', TRUE, current_timestamp, 1, current_timestamp, 1),
       (14, 'Germents', TRUE, current_timestamp, 1, current_timestamp, 1),
       (15, 'Classess', TRUE, current_timestamp, 1, current_timestamp, 1),
       (16, 'Graphics', TRUE, current_timestamp, 1, current_timestamp, 1),
       (17, 'Handicraft', TRUE, current_timestamp, 1, current_timestamp, 1),
       (18, 'Hospital', TRUE, current_timestamp, 1, current_timestamp, 1),
       (19, 'Hotel', TRUE, current_timestamp, 1, current_timestamp, 1),
       (20, 'Industries', TRUE, current_timestamp, 1, current_timestamp, 1),
       (21, 'Marbel', TRUE, current_timestamp, 1, current_timestamp, 1),
       (22, 'Medical', TRUE, current_timestamp, 1, current_timestamp, 1),
       (23, 'Online Trading', TRUE, current_timestamp, 1, current_timestamp, 1),
       (24, 'Organic', TRUE, current_timestamp, 1, current_timestamp, 1),
       (25, 'Paints', TRUE, current_timestamp, 1, current_timestamp, 1),
       (26, 'Pharma', TRUE, current_timestamp, 1, current_timestamp, 1),
       (27, 'Plating', TRUE, current_timestamp, 1, current_timestamp, 1),
       (28, 'Power Equip', TRUE, current_timestamp, 1, current_timestamp, 1),
       (29, 'Painting', TRUE, current_timestamp, 1, current_timestamp, 1),
       (30, 'Readymade Garments', TRUE, current_timestamp, 1, current_timestamp, 1),
       (31, 'Restaurant', TRUE, current_timestamp, 1, current_timestamp, 1),
       (32, 'Security', TRUE, current_timestamp, 1, current_timestamp, 1),
       (33, 'Seqing Machine', TRUE, current_timestamp, 1, current_timestamp, 1),
       (34, 'Spare Parts', TRUE, current_timestamp, 1, current_timestamp, 1),
       (35, 'Steel', TRUE, current_timestamp, 1, current_timestamp, 1),
       (36, 'Studio', TRUE, current_timestamp, 1, current_timestamp, 1),
       (37, 'Tents', TRUE, current_timestamp, 1, current_timestamp, 1),
       (38, 'Timber / Plywood', TRUE, current_timestamp, 1, current_timestamp, 1),
       (39, 'Trading', TRUE, current_timestamp, 1, current_timestamp, 1),
       (40, 'Tubewell', TRUE, current_timestamp, 1, current_timestamp, 1),
       (41, 'Tyres', TRUE, current_timestamp, 1, current_timestamp, 1),
       (42, 'Water Purifier', TRUE, current_timestamp, 1, current_timestamp, 1),
       (43, 'X-Ray Machine', TRUE, current_timestamp, 1, current_timestamp, 1),
       (44, 'Web Design', TRUE, current_timestamp, 1, current_timestamp, 1),
       (45, 'Watches', TRUE, current_timestamp, 1, current_timestamp, 1),
       (46, 'Tution', TRUE, current_timestamp, 1, current_timestamp, 1),
       (47, 'Travel / Transport', TRUE, current_timestamp, 1, current_timestamp, 1),
       (48, 'Tools', TRUE, current_timestamp, 1, current_timestamp, 1),
       (49, 'Textile', TRUE, current_timestamp, 1, current_timestamp, 1),
       (50, 'Sweets', TRUE, current_timestamp, 1, current_timestamp, 1),
       (51, 'Structure Design', TRUE, current_timestamp, 1, current_timestamp, 1),
       (52, 'Spices', TRUE, current_timestamp, 1, current_timestamp, 1),
       (53, 'Solar System', TRUE, current_timestamp, 1, current_timestamp, 1),
       (54, 'Seed', TRUE, current_timestamp, 1, current_timestamp, 1),
       (55, 'Saw Mill', TRUE, current_timestamp, 1, current_timestamp, 1),
       (56, 'Refrigeration', TRUE, current_timestamp, 1, current_timestamp, 1),
       (57, 'Propertyu Dealer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (58, 'Power Press', TRUE, current_timestamp, 1, current_timestamp, 1),
       (59, 'Polymer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (60, 'Placement', TRUE, current_timestamp, 1, current_timestamp, 1),
       (61, 'Petrol Pump', TRUE, current_timestamp, 1, current_timestamp, 1),
       (62, 'Packaging', TRUE, current_timestamp, 1, current_timestamp, 1),
       (63, 'Optics', TRUE, current_timestamp, 1, current_timestamp, 1),
       (64, 'Music', TRUE, current_timestamp, 1, current_timestamp, 1),
       (65, 'Marketing', TRUE, current_timestamp, 1, current_timestamp, 1),
       (66, 'Jewellery', TRUE, current_timestamp, 1, current_timestamp, 1),
       (67, 'Ice-Cream', TRUE, current_timestamp, 1, current_timestamp, 1),
       (68, 'Hostel', TRUE, current_timestamp, 1, current_timestamp, 1),
       (69, 'Hardware', TRUE, current_timestamp, 1, current_timestamp, 1),
       (70, 'Gym Equips', TRUE, current_timestamp, 1, current_timestamp, 1),
       (71, 'Grain Store', TRUE, current_timestamp, 1, current_timestamp, 1),
       (72, 'General Store', TRUE, current_timestamp, 1, current_timestamp, 1),
       (73, 'Furniture', TRUE, current_timestamp, 1, current_timestamp, 1),
       (74, 'Flour Mil', TRUE, current_timestamp, 1, current_timestamp, 1),
       (75, 'Finance', TRUE, current_timestamp, 1, current_timestamp, 1),
       (76, 'Fabrication', TRUE, current_timestamp, 1, current_timestamp, 1),
       (77, 'Electronics', TRUE, current_timestamp, 1, current_timestamp, 1),
       (78, 'Cycle', TRUE, current_timestamp, 1, current_timestamp, 1),
       (79, 'Crockery', TRUE, current_timestamp, 1, current_timestamp, 1),
       (80, 'Courier', TRUE, current_timestamp, 1, current_timestamp, 1),
       (81, 'Cinema / Theater', TRUE, current_timestamp, 1, current_timestamp, 1),
       (82, 'Ceramic', TRUE, current_timestamp, 1, current_timestamp, 1),
       (83, 'Book-Stationery', TRUE, current_timestamp, 1, current_timestamp, 1),
       (84, 'Auto Dealer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (85, 'Shoes', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- SERVICES ---------------------------------------------
insert into mst_service (service_id, service, active, created_at, created_by, updated_at, modified_by)
VALUES (1, 'Software Engineer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (2, 'Interior Decorator', TRUE, current_timestamp, 1, current_timestamp, 1),
       (3, 'Computer Operator', TRUE, current_timestamp, 1, current_timestamp, 1),
       (4, 'Chartered Accountant', TRUE, current_timestamp, 1, current_timestamp, 1),
       (5, 'Computer Engineer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (6, 'Graphics Designer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (7, 'Hardware Engineer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (8, 'Tax Consultant', TRUE, current_timestamp, 1, current_timestamp, 1),
       (9, 'Actor / Actress', TRUE, current_timestamp, 1, current_timestamp, 1),
       (10, 'Advocate / Lawyer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (11, 'Author / Write', TRUE, current_timestamp, 1, current_timestamp, 1),
       (12, 'Coach / Bodybuilders', TRUE, current_timestamp, 1, current_timestamp, 1),
       (13, 'Agent / Broker', TRUE, current_timestamp, 1, current_timestamp, 1),
       (14, 'Director / Manager', TRUE, current_timestamp, 1, current_timestamp, 1),
       (15, 'Architecture', TRUE, current_timestamp, 1, current_timestamp, 1),
       (16, 'Artist', TRUE, current_timestamp, 1, current_timestamp, 1),
       (17, 'BPO', TRUE, current_timestamp, 1, current_timestamp, 1),
       (18, 'Caterer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (19, 'Designer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (20, 'Doctor', TRUE, current_timestamp, 1, current_timestamp, 1),
       (21, 'Electrictrician', TRUE, current_timestamp, 1, current_timestamp, 1),
       (22, 'Guide', TRUE, current_timestamp, 1, current_timestamp, 1),
       (23, 'Accountant', TRUE, current_timestamp, 1, current_timestamp, 1),
       (24, 'Advisor', TRUE, current_timestamp, 1, current_timestamp, 1),
       (25, 'Arms', TRUE, current_timestamp, 1, current_timestamp, 1),
       (26, 'Astrologer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (27, 'Beautician', TRUE, current_timestamp, 1, current_timestamp, 1),
       (28, 'Carpenter', TRUE, current_timestamp, 1, current_timestamp, 1),
       (29, 'Contractor', TRUE, current_timestamp, 1, current_timestamp, 1),
       (30, 'Driver', TRUE, current_timestamp, 1, current_timestamp, 1),
       (31, 'Mechanic', TRUE, current_timestamp, 1, current_timestamp, 1),
       (32, 'Painter', TRUE, current_timestamp, 1, current_timestamp, 1),
       (33, 'Plumber', TRUE, current_timestamp, 1, current_timestamp, 1),
       (34, 'Salesman', TRUE, current_timestamp, 1, current_timestamp, 1),
       (35, 'Tailor', TRUE, current_timestamp, 1, current_timestamp, 1),
       (36, 'Teacher', TRUE, current_timestamp, 1, current_timestamp, 1),
       (37, 'Musician', TRUE, current_timestamp, 1, current_timestamp, 1),
       (38, 'Photographer', TRUE, current_timestamp, 1, current_timestamp, 1),
       (39, 'Professor', TRUE, current_timestamp, 1, current_timestamp, 1),
       (40, 'Singer', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- GENDER ---------------------------------------------
insert into mst_gender(gender_id, gender, active, created_at, created_by, updated_at, modified_by, created_ip,
                       modified_ip)
VALUES (1, 'Male', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (2, 'Female', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

-- ------------------------------------------- MARITAL STATUS -------------------------------------
insert into mst_marital_status (marital_status_id, marital_status, active, created_at, created_by, updated_at,
                                modified_by)
VALUES (1, 'Single', TRUE, current_timestamp, 1, current_timestamp, 1),
       (2, 'Married', TRUE, current_timestamp, 1, current_timestamp, 1),
       (3, 'Divorced', TRUE, current_timestamp, 1, current_timestamp, 1),
       (4, 'Widowed', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- RELATIONSHIP ---------------------------------------
insert into mst_relationship (relationship_id, relationship, active, created_at, created_by, updated_at, modified_by)
VALUES (1, 'Father', TRUE, current_timestamp, 1, current_timestamp, 1),
       (2, 'Mother', TRUE, current_timestamp, 1, current_timestamp, 1),
       (3, 'Brother', TRUE, current_timestamp, 1, current_timestamp, 1),
       (4, 'Sister', TRUE, current_timestamp, 1, current_timestamp, 1),
       (5, 'Husband', TRUE, current_timestamp, 1, current_timestamp, 1),
       (6, 'Wife', TRUE, current_timestamp, 1, current_timestamp, 1),
       (7, 'Daughter', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- COUNTRY ---------------------------------------------
insert into mst_country (country_id, country, country_code, active, created_at,
                         updated_at, created_by, modified_by, created_ip, modified_ip)
VALUES (1, 'Afghanistan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (2, 'Albania', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (3, 'Algeria', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (4, 'American Samoa', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (5, 'Andorra', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (6, 'Angola', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (7, 'Anguilla', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (8, 'Antigua and Barbuda', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (9, 'Argentina', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (10, 'Armenia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (11, 'Aruba', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (12, 'Australia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (13, 'Austria', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (14, 'Azerbaijan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (15, 'Bahamas', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (16, 'Bahrain', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (17, 'Bangladesh', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (18, 'Barbados', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (19, 'Belarus', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (20, 'Belgium', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (21, 'Belize', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (22, 'Benin', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (23, 'Bermuda', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (24, 'Bhutan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (25, 'Bolivia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (26, 'Bosnia and Herzegovina', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (27, 'Botswana', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (28, 'Bouvet Island', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (29, 'Brazil', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (30, 'British Indian Ocean territory', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (31, 'Brunei Darussalam', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (32, 'Bulgaria', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (33, 'Burkina Aso', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (34, 'Burundi', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (35, 'Cambodia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (36, 'Cameroon', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (37, 'Canada', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (38, 'Cape Verde', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (39, 'Cayman Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (40, 'Central African Republic', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (41, 'Chad', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (42, 'Chile', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (43, 'China', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (44, 'Christmas Island', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (45, 'Cocos Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (46, 'Colombia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (47, 'Comoros', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (48, 'Congo', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (49, 'Congo, Democratic Republic', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (50, 'Cook Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (51, 'Costa Rica', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (52, 'Croatia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (53, 'Cuba', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (54, 'Cyprus', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (55, 'Czech Republic', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (56, 'Denmark', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (57, 'Djibouti', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (58, 'Dominica', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (59, 'Dominican Republic', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (60, 'Ecuador', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (61, 'Egypt', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (62, 'El Salvador', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (63, 'Equatorial Guinea', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (64, 'Eritrea', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (65, 'Estonia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (66, 'Ethiopia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (67, 'Falkland Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (68, 'Faroe Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (69, 'Fiji', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (70, 'Finland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (71, 'France', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (72, 'French Guiana', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (73, 'French Polynesia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (74, 'French Southern Territories', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (75, 'Gabon', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (76, 'Gambia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (77, 'Georgia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (78, 'Germany', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (79, 'Ghana', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (80, 'Gibraltar', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (81, 'Greece', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (82, 'Greenland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (83, 'Grenada', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (84, 'Guadeloupe', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (85, 'Guam', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (86, 'Guatemala', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (87, 'Guinea', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (88, 'Guinea-Bissau', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (89, 'Guyana', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (90, 'Haiti', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (91, 'Heard and McDonald Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (92, 'Honduras', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (93, 'Hong Kong', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (94, 'Hungary', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (95, 'Iceland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (96, 'India', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (97, 'Indoesia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (98, 'Iran', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (99, 'Iraq', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (100, 'Ireland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (101, 'Israel', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (102, 'Italy', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (103, 'Ivory Coast', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (104, 'Jamaica', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (105, 'Japan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (106, 'Jordan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (107, 'Kazakhstan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (108, 'Kenya', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (109, 'Kiribati', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (110, 'Korea (north)', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (111, 'Korea (south)', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (112, 'Kuwait', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (113, 'Kyrgyzstan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (114, 'Lao Peoples Democratic Republic', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (115, 'Latvia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (116, 'Lebanon', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (117, 'Lesotho', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (118, 'Liberia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (119, 'Libyan Arab Jamahiriya', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (120, 'Liechtenstein', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (121, 'Lithuania', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (122, 'Luxembourg', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (123, 'Macao', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (124, 'Macedonia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (125, 'Madagascar', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (126, 'Malawi', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (127, 'Malaysia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (128, 'Maldives', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (129, 'Mali', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (130, 'Malta', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (131, 'Marshall Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (132, 'Martinique', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (133, 'Mauritania', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (134, 'Mauritius', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (135, 'Mayotte', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (136, 'Mexico', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (137, 'Micronesia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (138, 'Moldova', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (139, 'Monaco', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (140, 'Mongolia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (141, 'Montserrat', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (142, 'Morocco', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (143, 'Mozambique', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (144, 'Myanmar', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (145, 'Namibia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (146, 'Nauru', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (147, 'Nepal', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (148, 'Netherlands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (149, 'Netherlands Antilles', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (150, 'New Caledonia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (151, 'New Zealand', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (152, 'Nicaragua', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (153, 'Niger', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (154, 'Nigeria', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (155, 'Niue', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (156, 'Norfolk Island', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (157, 'Northern Mariana Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (158, 'Norway', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (159, 'Oman', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (160, 'Pakistan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (161, 'Palau', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (162, 'Palestinian Territories', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (163, 'Panama', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (164, 'Papua New Guinea', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (165, 'Paraguay', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (166, 'Peru', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (167, 'Philippines', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (168, 'Pitcairn', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (169, 'Poland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (170, 'Portugal', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (171, 'Puerto Rico', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (172, 'Qatar', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (173, 'Reunion', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (174, 'Romania', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (175, 'Russian Federation', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (176, 'Rwanda', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (177, 'Saint Helena', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (178, 'Saint Kitts and Nevis', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (179, 'Saint Lucia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (180, 'Saint Pierre and Miquelon', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (181, 'Saint Vincent and the Grenadines', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (182, 'Samoa', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (183, 'San Marino', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (184, 'Sao Tome and Principe', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (185, 'Saudi Arabia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (186, 'Senegal', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (187, 'Serbia and Montenegro', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (188, 'Seychelles', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (189, 'Sierra Leone', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (190, 'Singapore', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (191, 'Slovakia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (192, 'Slovenia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (193, 'Solomon Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (194, 'Somalia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (195, 'South Africa', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (196, 'South Georgia and the South Sandwich Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1,
        ':0', ':0'),
       (197, 'Spain', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (198, 'Sri Lanka', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (199, 'Sudan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (200, 'Suriname', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (201, 'Svalbard and Jan Mayen Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (202, 'Swaziland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (203, 'Sweden', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (204, 'Switzerland', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (205, 'Syria', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (206, 'Taiwan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (207, 'Tajikistan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (208, 'Tanzania', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (209, 'Thailand', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (210, 'Togo', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (211, 'Tokelau', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (212, 'Tonga', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (213, 'Trinidad and Tobago', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (214, 'Tunisia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (215, 'Turkey', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (216, 'Turkmenistan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (217, 'Turks and Caicos Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (218, 'Tuvalu', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (219, 'Uganda', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (220, 'Ukraine', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (221, 'United Arab Emirates', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (222, 'United Kingdom', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (223, 'United States', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (224, 'Uruguay', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (225, 'Uzbekistan', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (226, 'Vanuatu', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (227, 'Venezuela', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (228, 'Vietnam', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (229, 'Virgin Islands (British)', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (230, 'Virgin Islands (US)', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (231, 'Wallis and Futuna Islands', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (232, 'Western Sahara', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (233, 'Yemen', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (234, 'Zambia', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (235, 'Zimbabwe', NULL, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0');

-- ------------------------------------------- STATE ---------------------------------------------
insert into mst_state (state_id, code, state, country_id, active, created_at, updated_at, created_by, modified_by,
                       created_ip, modified_ip)
VALUES (1, 96, 'Jammu & Kashmir', 1, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (2, 96, 'Himachal Pradesh', 2, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (3, 96, 'Punjab', 3, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (4, 96, 'Chandigarh', 4, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (5, 96, 'Uttarakhand', 5, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (6, 96, 'Haryana', 6, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (7, 96, 'Delhi', 7, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (8, 96, 'Rajasthan', 8, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (9, 96, 'Uttar Pradesh', 9, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (10, 96, 'Bihar', 10, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (11, 96, 'Sikkim', 11, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (12, 96, 'Arunachal Pradesh', 12, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (13, 96, 'Nagaland', 13, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (14, 96, 'Manipur', 14, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (15, 96, 'Mizoram', 15, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (16, 96, 'Tripura', 16, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (17, 96, 'Meghalaya', 17, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (18, 96, 'Assam', 18, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (19, 96, 'West Bengal', 19, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (20, 96, 'Jharkhand', 20, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (21, 96, 'Orissa', 21, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (22, 96, 'Chhattisgarh', 22, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (23, 96, 'Madhya Pradesh', 23, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (24, 96, 'Gujarat', 24, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (25, 96, 'Daman & Diu', 25, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (26, 96, 'Dadra & Nagar Haveli', 26, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (27, 96, 'Maharashtra', 27, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (28, 96, 'Andhra Pradesh', 28, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (29, 96, 'Karnataka', 29, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (30, 96, 'Goa', 30, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (31, 96, 'Lakshadweep', 31, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (32, 96, 'Kerala', 32, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (33, 96, 'Tamil Nadu', 33, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (34, 96, 'Puducherry', 34, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (35, 96, 'Andaman & Nicobar Islands', 35, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (36, 96, 'Telengana', 36, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (37, 96, 'Andrapradesh', 37, TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0');

-- ------------------------------------------- DISTRICT ---------------------------------------------
insert into mst_district (district_id, state_id, district, active, created_at, updated_at, created_by, modified_by,
                          created_ip, modified_ip)
VALUES (1, 8, 'Jalore', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (2, 8, 'Sirohi', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (3, 8, '3', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (4, 8, 'Pali', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (5, 8, 'Rajsamand', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (6, 8, 'banaskantha', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (7, 8, 'Dhara', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0');

insert into mst_district (district_id, state_id, district, active, created_at, updated_at, created_by, modified_by,
                          created_ip, modified_ip)
VALUES (11, 27, 'Mumbai', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (12, 27, 'Thane', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0');

insert into mst_district (district_id, state_id, district, active, created_at, updated_at, created_by, modified_by,
                          created_ip, modified_ip)
VALUES (13, 23, 'Ratlam', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (14, 24, 'Dantivada', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0'),
       (15, 24, 'Ahmedabad', TRUE, current_timestamp, current_timestamp, 1, 1, ':0', ':0');

-- ------------------------------------------- CITY VILLAGE ---------------------------------------------
insert into mst_city_village (city_village_id, type_id, city_vilage, district_id, pin_code, std_code, active,
                              created_at, created_by, updated_at, modified_by, created_ip, modified_ip)
VALUES (1, 1, 'Agawari', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (2, 1, 'Ajari', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (3, 1, 'Andor', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (4, 1, 'Amirama', '3', '312401', '1473', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (5, 1, 'Asava', 2, '307511', '2975', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (6, 1, 'Aipura', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (7, 1, 'Aakorapadar', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (8, 1, 'Aana', 4, '306703', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (9, 1, 'Aalpa', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (10, 1, 'Ahore', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (11, 1, 'Isali', 4, '306026', '2935', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (12, 1, 'Uthnam', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (13, 1, 'Umedpur', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (14, 1, 'Karavnaa', 4, '307006', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (15, 1, 'Kalapura', 1, '307515', '2990', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (16, 1, 'Kawarada', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (17, 1, 'Kanpura', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (18, 1, 'Kamba', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (19, 1, 'Kalndri', 2, '307802', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (20, 1, 'Kasindra', 2, '307023', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (21, 1, 'Kirva', 4, '306422', '2932', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (22, 1, 'Kesua', 2, '307512', '2975', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (23, 1, 'Kelashnagar', 2, '307801', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (24, 1, 'Kota (Baliyan)', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (25, 1, 'Kotdi', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (26, 1, 'Korta', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (27, 1, 'Kolpura', 4, '306022', '2935', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (28, 1, 'Koliwada', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (29, 1, 'Koselaw', 4, '306710', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (30, 1, 'Kurshnajhang (Meda)', 2, '307001', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0',
        ':0'),
       (31, 1, 'Kandra', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (32, 1, 'Kimada', 4, '306710', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (33, 1, 'Kimel', 4, '306115', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (34, 1, 'Kiwada', 4, '306502', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (35, 1, 'Kiwandi', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (36, 1, 'Kudala', 4, '306116', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (37, 1, 'Gangawa', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (38, 1, 'Galthani', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (39, 1, 'Girali', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (40, 1, 'Guda Balota', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (41, 1, 'Guda Maharamji', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (42, 1, 'Godan', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (43, 1, 'Gol', 2, '307001', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (44, 1, 'Ghanerao', 4, '306704', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (45, 1, 'Cherli', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (46, 1, 'Chawarcha', 1, '343001', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (47, 1, 'Chanchodi', 4, '306115', '2932', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (48, 1, 'Chanod', 4, '306602', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (49, 1, 'Chandana', 1, '343024', '2973', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (50, 1, 'Chaudhari', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (51, 1, 'Chamundari', 4, '306504', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (52, 1, 'Charbhuja', '5', '313333', '2954', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (53, 1, 'Chiparwada', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (54, 1, 'Chibagoaw', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (55, 1, 'Janapur', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (56, 1, 'Jhakhoda', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (57, 1, 'Jhato Ka Guda', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (58, 1, 'Javal', 2, '307801', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (59, 1, 'Junna', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (60, 1, 'Jela', 2, '307802', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (61, 1, 'Joghpur', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (62, 1, 'Joda (Agawari)', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (63, 1, 'Jhadholi', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (64, 1, 'Dongurli', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (65, 1, 'Dhalop', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (66, 1, 'Takatghad', 4, '306912', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (67, 1, 'Tavri', 2, '307802', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (68, 1, 'Thavla', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (69, 1, 'Thumba', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (70, 1, 'Dantigoan', 7, '454116', '7296', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (71, 1, 'Dayalpura', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (72, 1, 'Degaon', 1, '343025', '2973', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (73, 1, 'Dujana', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (74, 1, 'Dudni', 4, '306504', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (75, 1, 'Deldar', 2, '307801', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (76, 1, 'Devli', 4, '306024', '2935', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (77, 1, 'Desuri', 4, '306703', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (78, 1, 'Dolpura', 2, '307026', '2975', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (79, 1, 'Ghani', 4, '306116', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (80, 1, 'Naya Sanwada', 2, '307021', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (81, 1, 'Nadol', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (82, 1, 'Nana', 4, '306504', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (83, 1, 'Narlai', 4, '306703', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (84, 1, 'Navdiya', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (85, 1, 'Nipal', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (86, 1, 'Nouvi', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (87, 1, 'Parakhiya', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (88, 1, 'Patava', 4, '306707', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (89, 1, 'Padarli', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (90, 1, 'Paldi ', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (91, 1, 'Pavtha', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (92, 1, 'Pava', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (93, 1, 'Pichava', 4, '306115', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (94, 1, 'Pindharadha', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (95, 1, 'Pindhiya', 4, '306115', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (96, 1, 'Peshua', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (97, 1, 'Pomava', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (98, 1, 'Posaliya', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (99, 1, 'Fatapura', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (100, 1, 'Falna ', 4, '306116', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (101, 1, 'Bhadgoan', 2, '307027', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (102, 1, 'Bada ', 4, '306707', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (103, 1, 'Barod', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (104, 1, 'Basant', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (105, 1, 'Basantgadh', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (106, 1, 'Bokhali', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (107, 1, 'Bogdhi', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (108, 1, 'Bagra', 1, '343025', '2973', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (109, 1, 'Botha', 4, '306503', '2935', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (110, 1, 'Badanwari', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (111, 1, 'Babogoan', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (112, 1, 'Bamnera', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (113, 1, 'Barva', 4, '306706', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (114, 1, 'Barewada', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (115, 1, 'Bali', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (116, 1, 'Bhichawadi', 1, '343001', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (117, 1, 'Bhijhowa', 4, '306601', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (118, 1, 'Birami', 4, '306115', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (119, 1, 'Bijapur', 4, '306707', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (120, 1, 'Budtar', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (121, 1, 'Boya', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (122, 1, 'Bhandar', 4, '306504', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (123, 1, 'Barundra', 4, '306901', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (124, 1, 'Bathund', 4, '306707', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (125, 1, 'Bhadras', 4, '306702', '29934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (126, 1, 'Bhavri', 2, '307041', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (127, 1, 'Bhitwada', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (128, 1, 'Bhiitgaon', 2, '307801', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (129, 1, 'Bhooti', 1, '307030', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (130, 1, 'Bhetala', 1, '343024', '2973', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (131, 1, 'Bhev', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (132, 1, 'Bhenswara', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (133, 1, 'Mandwariya', 2, '307801', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (134, 1, 'Mandal', 4, '306115', '2932', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (135, 1, 'Madni', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (136, 1, 'Mada', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (137, 1, 'Madhopura', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (138, 1, 'Malpura', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (139, 1, 'Malari', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (140, 1, 'Mithdi', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (141, 1, 'Mundara', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (142, 1, 'Mokapura', 4, '303115', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (143, 1, 'Morkha', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (144, 1, 'Morli', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (145, 1, 'Morana', 5, '313333', '2954', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (146, 1, 'Monka', 1, '343025', '2973', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (147, 1, 'Rasiyavash', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (148, 1, 'Rani ', 4, '306115', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (149, 1, 'Rani ', 4, '306115', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (150, 1, 'Ramnagar', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (151, 1, 'Rodhla', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (152, 1, 'Rovada', 2, '307028', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (153, 1, 'Rohidha', 2, '307024', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (154, 1, 'Lalrai', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (155, 1, 'Lunawa', 4, '306706', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (156, 1, 'Lothiwada', 2, '307801', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (157, 1, 'Vandar', 4, '306502', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (158, 1, 'Varkana', 4, '306601', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (159, 1, 'Kaldara', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (160, 1, 'Vagshen', 2, '307043', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (161, 1, 'Vasa', 2, '307024', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (162, 1, 'Vikanwas', 1, '307515', '2990', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (163, 1, 'Vingrla', 4, '306603', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (164, 1, 'Verampura', 4, '306504', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (165, 1, 'Verwada', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (166, 1, 'Vadiya', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (167, 1, 'Valengari', 2, '307001', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (168, 1, 'Velar', 4, '306504', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (169, 1, 'Sankhwali', 1, '307029', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (170, 1, 'Shivganj', 2, '307027', '2976', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (171, 1, 'Shiwatlav', 4, '306705', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (172, 1, 'Sladriya', 2, '307027', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (173, 1, 'Savli', 2, '307801', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (174, 1, 'Sanderao', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (175, 1, 'Shanthu', 1, '343026', '2973', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (176, 1, 'Sadar', 4, '306706', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (177, 1, 'Sadri', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (178, 1, 'Samuja', 1, '307029', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (179, 1, 'Sarlriya', 4, '306117', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (180, 1, 'Sindheru', 4, '306708', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (181, 1, 'Siana', 1, '343024', '2973', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (182, 1, 'Sirohi', 2, '307001', '2972', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (183, 1, 'Sirohi ', 2, '307021', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (184, 1, 'Sivera', 2, '307022', '2971', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (185, 1, 'Sutharo ', 4, '306702', '2934', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (186, 1, 'Sumerpur', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (187, 1, 'Sdriya', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (188, 1, 'Sewadi', 4, '306707', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (189, 1, 'Sokada', 4, '306706', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (190, 1, 'Saysli', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (191, 1, 'Sonpura', 4, '306902', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (192, 1, 'Sri ', 4, '306701', '2938', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (193, 1, 'Harji', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (194, 1, 'Hariyali', 1, '307030', '2978', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (195, 1, 'Jetawada', 2, '307513', '2975', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (196, 1, 'Takathadh', 4, '306912', '2933', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (197, 1, 'Pounthawada', 6, '385546', '2748', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (198, 1, 'Dhaniyawada', 6, '385505', '2748', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (199, 1, 'Bhanaotra', 6, '385545', '2748', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (200, 1, 'Mandar', 2, '307513', '2975', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (201, 1, 'Maalpura', 2, '307513', '2975', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (202, 1, 'Raniwara', 1, '343040', '2990', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (203, 1, 'Revdar', 2, '307514', '2975', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (204, 1, 'Vadgaon ', 1, '343048', '2990', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

insert into mst_city_village (city_village_id, type_id, city_vilage, district_id, pin_code, std_code, active,
                              created_at, created_by, updated_at, modified_by, created_ip, modified_ip)
VALUES (205, 2, 'Churchgate', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (206, 2, 'Marine Lines', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (207, 2, 'Charni Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (208, 2, 'Grant Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (209, 2, 'Mumbai Central', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (210, 2, 'Maha Laxmi', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (211, 2, 'Lower Parel', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (212, 2, 'Elphinstone Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (213, 2, 'Dadar', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (214, 2, 'Matunga Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (215, 2, 'Mahim Junction', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (216, 2, 'Bandra', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (217, 2, 'Khar Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (218, 2, 'Santacruz', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (219, 2, 'Vile Parle', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (220, 2, 'Andheri', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (221, 2, 'Jogeshwari', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (222, 2, 'Goregaon', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (223, 2, 'Malad', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (224, 2, 'Kandivili', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (225, 2, 'Borivali', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (226, 2, 'Dahisar', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (227, 2, 'Mira Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (228, 2, 'Bhayander', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (229, 2, 'Nalgaon', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (230, 2, 'Vasai Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (231, 2, 'Nala Sopara', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (232, 2, 'Virar', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (233, 2, 'Vaitarna', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (234, 2, 'Saphale', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (235, 2, 'Kelve Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (236, 2, 'Palghar', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (237, 2, 'Umroli', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (238, 2, 'Boisar', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (239, 2, 'Vangaon', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (240, 2, 'Dahanu Road', 11, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (241, 2, 'Thane', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (242, 2, 'Dighe', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (243, 2, 'Airoli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (244, 2, 'Rabale', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (245, 2, 'Ghansoli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (246, 2, 'Kopar ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (247, 2, 'Turbhe', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (248, 2, 'Sanpada', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (249, 2, 'Vashi', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (250, 2, 'Jui ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (251, 2, 'Nerul', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (252, 2, 'Seawoods ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (253, 2, 'Belapur ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (254, 2, 'Kharghar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (255, 2, 'Mansarovar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (256, 2, 'Khandeshwar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (257, 2, 'Panvel ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (258, 2, 'CST', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (259, 2, 'Masjid', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (260, 2, 'Sandhurt ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (261, 2, 'Docyard ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (262, 2, 'Reay ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (263, 2, 'Cotton ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (264, 2, 'Sewri', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (265, 2, 'Vadala ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (266, 2, 'King ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (267, 2, 'Guru ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (268, 2, 'Chunabhatti', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (269, 2, 'Kurla ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (270, 2, 'Tilaknagar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (271, 2, 'Chembur', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (272, 2, 'Govandi', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (273, 2, 'Mankhurd', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (274, 2, 'Vashi', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (275, 2, 'Vasai ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (276, 2, 'Juchandr', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (277, 2, 'Kaman ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (278, 2, 'Kharbav', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (279, 2, 'Bhiwandi ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (280, 2, 'Kopar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (281, 2, 'Diva ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (282, 2, 'Mumbai ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (283, 2, 'Masjid', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (284, 2, 'Sandhurst ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (285, 2, 'Byculla ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (286, 2, 'Chinchpokli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (287, 2, 'Currey ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (288, 2, 'Parel', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (289, 2, 'Dadar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (290, 2, 'Matunga', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (291, 2, 'Sion', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (292, 2, 'Kurla', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (293, 2, 'Vidyavihar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (294, 2, 'Ghatkopar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (295, 2, 'Vikhroli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (296, 2, 'Kanjur ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (297, 2, 'Bhandup', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (298, 2, 'Nahur', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (299, 2, 'Mulund', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (300, 2, 'Thane', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (301, 2, 'Kalva', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (302, 2, 'Mumbra', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (303, 2, 'Diva ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (304, 2, 'Kopar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (305, 2, 'Dombivali', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (306, 2, 'Thakurli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (307, 2, 'Kalyan ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (308, 2, 'Shahad', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (309, 2, 'Ambivali', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (310, 2, 'Titwala', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (311, 2, 'Khadavali', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (312, 2, 'Vasind', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (313, 2, 'Asangaon', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (314, 2, 'Atgaon', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (315, 2, 'Thansit', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (316, 2, 'Khardi', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (317, 2, 'Oombermali', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (318, 2, 'Kasara', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (319, 2, 'Vithalwadi', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (320, 2, 'Ulhasnagar', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (321, 2, 'Ambernath', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (322, 2, 'Badlapur', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (323, 2, 'Vangani', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (324, 2, 'Shelu', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (325, 2, 'Nerul', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (326, 2, 'Bhipuri ', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (327, 2, 'Karjat', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (328, 2, 'Palasdari', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (329, 2, 'Kelavli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (330, 2, 'Dolavli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (331, 2, 'Lowjee', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (332, 2, 'Khopoli', 12, NULL, NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

insert into mst_city_village (city_village_id, type_id, city_vilage, district_id, pin_code, std_code, active,
                              created_at, created_by, updated_at, modified_by, created_ip, modified_ip)
VALUES (333, 1, 'Ringnod', 13, '457336', NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (334, 1, 'Panthawada', 14, '385545', NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (335, 1, 'Ahmedabad', 15, '380019', NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');


-- ------------------------------------------- POST ---------------------------------------------
insert into mst_post (post_id, post_name, active, created_at, created_by, updated_at, modified_by, created_ip,
                      modified_ip)
VALUES (1, 'Guardian', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (2, 'Chairman', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (3, 'Vice Chairman', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (4, 'General Secretary', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (5, 'Treasurer', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (6, 'Joint Treasurer', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (7, 'Secretary', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (8, 'Joint Secretary', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (9, 'Management', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (10, 'Advisor', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (11, 'Accountants', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

-- ------------------------------------------- ADDRESS TYPE ---------------------------------------------
insert into mst_address_type(address_type_id, address_type, active, created_at, created_by, updated_at, modified_by)
VALUES (1, 'Permanent Address', TRUE, current_timestamp, 1, current_timestamp, 1),
       (2, 'Communication Address', TRUE, current_timestamp, 1, current_timestamp, 1),
       (3, 'Office Address', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- CONTACT NUMBER TYPE ---------------------------------------------
insert into mst_contact_type (contact_type_id, contact_type, active, created_at, created_by, updated_at, modified_by,
                              created_ip, modified_ip)
VALUES (1, 'Mobile Number', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (2, 'Alternate Number', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (3, 'Landline Number', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (4, 'Office Number', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

-- ------------------------------------------- Religion ---------------------------------------------
insert into mst_religion (religion_id, religion, active, created_at, created_by, updated_at, modified_by)
VALUES (1, 'Hindu', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Gotra ---------------------------------------------
insert into mst_gotra (gotra_id, gotra, active, created_at, created_by, updated_at, modified_by)
VALUES (1, 'Parihar', TRUE, current_timestamp, 1, current_timestamp, 1),
       (2, 'Chouhan', TRUE, current_timestamp, 1, current_timestamp, 1),
       (3, 'Solanki', TRUE, current_timestamp, 1, current_timestamp, 1),
       (4, 'Parmar', TRUE, current_timestamp, 1, current_timestamp, 1),
       (5, 'Tripasta', TRUE, current_timestamp, 1, current_timestamp, 1),
       (6, 'Rathod', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Addiction ---------------------------------------------
insert into mst_addiction (addiction_id, addiction, active, created_at, created_by, updated_at, modified_by)
VALUES (1, 'Tobacco', TRUE, current_timestamp, 1, current_timestamp, 1),
       (2, 'Alcohol', TRUE, current_timestamp, 1, current_timestamp, 1),
       (3, 'Smoking', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Caste ---------------------------------------------
insert into mst_caste (caste_id, caste, active, created_at, created_by, updated_at, modified_by, created_ip,
                       modified_ip)
VALUES (1, 'Suthar', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

-- ------------------------------------------- Request Status ---------------------------------------------
insert into mst_matrimonial_requested_status (requested_status_id, status, active, created_at, created_by, updated_at,
                                              modified_by, created_ip, modified_ip)
VALUES (1, 'Accepted', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (2, 'Rejected', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (3, 'Ignore', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

-- ------------------------------------------- Matrimonial Status ---------------------------------------------
INSERT INTO mst_matrimonial_status (matrimonial_status_id, status, active, created_at, created_by, updated_at,
                                    modified_by, created_ip, modified_ip)
VALUES (1, 'Waiting For Approval', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (2, 'Approved', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (3, 'Rejected', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (4, 'Closed', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

-- ------------------------------------------- Education Degree ---------------------------------------------
insert into mst_education_degree (education_degree_id, degree, active, created_at, created_by, updated_at, modified_by,
                                  created_ip, modified_ip)
VALUES (1, 'No Education', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (2, 'Below 5th Class', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (3, '8th Pass', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (4, '10th (SSC) Pass', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (5, '12th (HSC) Pass', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (6, 'B. Com.', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (7, 'B. E.', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

-- ------------------------------------------- Media Src ---------------------------------------------
insert into mst_media_src (media_src_id, media_src, active, created_at, created_by, updated_at, modified_by)
VALUES (1, 'Server', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Media Type ---------------------------------------------
insert into mst_media_type (media_type_id, media_type, active, created_at, created_by, updated_at, modified_by)
VALUES (1, 'Image', TRUE, current_timestamp, 1, current_timestamp, 1),
       (2, 'Video', TRUE, current_timestamp, 1, current_timestamp, 1);

-- ------------------------------------------- Raasi ---------------------------------------------
insert into mst_raasi (raasi_id, raasi, active, created_at, created_by, updated_at, modified_by, created_ip,
                       modified_ip)
VALUES (1, 'Mesh (Aries)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (2, 'Varishabha (Taurus)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (3, 'Mithuna (Gemini)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (4, 'Karka (Cancer)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (5, 'Simha (Leo)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (6, 'Kanya (Virgo)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (7, 'Tula (Libra)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (8, 'Vrischika (Scorpio)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (9, 'Dhanur (Sagittarious)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (10, 'Makara (Capricorn)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (11, 'Kumbha (Aquarius)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (12, 'Meena (Pisces)', TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

-- ------------------------------------------- Table ---------------------------------------------
INSERT INTO mst_table (table_id, table_name, active, created_at, created_by, updated_at, modified_by)
VALUES (1, 'txn_events', true, NOW(), 1, NOW(), 1),
       (2, 'txn_familys', true, NOW(), 1, NOW(), 1),
       (3, 'txn_temples', true, NOW(), 1, NOW(), 1),
       (4, 'txn_mandals', true, NOW(), 1, NOW(), 1),
       (5, 'mst_admin_users', true, NOW(), 1, NOW(), 1);

-- ------------------------------------------- TEMPLE ---------------------------------------------
insert into txn_address (address_id, address_type_id, address,
                         pin_code, city_village_id, latitude, longitude, active,
                         created_ip, modified_ip, created_at, updated_at, district_id, state_id,country_id, created_by, modified_by)
VALUES (1, 3, 'Vishwakarma mandir', '306706', 113, 25.1264051, 73.3157686, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (2, 3, 'Ringnod', '457336', 333, 23.7375145, 75.1755614, TRUE, ':0', ':0', now(), now(), 2, 8, 96,1,1),
       (3, 3, 'Sutharo Ka Vas', '343001', 193, 25.2901106, 72.8548346, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (4, 3, 'Sutharon Ka Vas', '307029', 10, 25.3688712, 72.777957, TRUE, ':0', ':0', now(), now(), 4, 8, 96,1,1),
       (5, 3, 'Athmanavas', '343025', 108, 25.195514, 72.5850005, TRUE, ':0', ':0', now(), now(), 2, 8, 96,1,1),
       (8, 3, 'Siana- Sirohi Main Road, Varada', '307801', 165, 25.0044297, 72.4165222, TRUE, ':0', ':0', now(), now(), 2, 8, 96,1,1),
       (9, 3, 'Sutharo Ka Vas, New Nehru Nagar', '307027', 170, 25.13688, 73.0676513, TRUE, ':0', ':0', now(), now(), 2, 8, 96,1,1),
       (12, 3, 'Dantrai', '307512', 22, 24.7123047, 72.5184889, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (13, 3, 'Suthar Vaas St, Vedhaynath Colony', '307001', 182, 24.8829412, 72.8615207, TRUE, ':0', ':0', now(), now(), 13, 23, 96,1,1),
       (14, 3, 'Panthawada', '385545', 334, 24.4955766, 72.2991274, TRUE, ':0', ':0', now(), now(), 14, 24, 96,1,1),
       (15, 3, 'Ram Nagar, Sabarmati', '380019', 335, 23.0930829, 72.5822966, TRUE, ':0', ':0', now(), now(), 15, 25, 96,1,1);

INSERT INTO mst_temple (temple_id, address_id, temple_name, image_path, active, created_at, created_by, updated_at, modified_by, created_ip, modified_ip)
VALUES (1, 1, 'बारवा', null, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (2, 2, 'रिगनोंगद', null, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (3, 3, 'हरजी', null, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (4, 4, 'आहोर', null, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (5, 5, 'बागरा', NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (8, 8, 'सिरोही', NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (9, 9, 'शिंवगंज', NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (12, 12, 'दांतराई', NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (13, 13, 'पामेरा', NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (14, 14, 'पांथावाडा', NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (15, 15, 'साबरमती', NULL, TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

-- ------------------------------------------- MANDAL ---------------------------------------------
INSERT INTO txn_address (address_id, address_type_id, address,
                         pin_code, city_village_id, latitude, longitude, active,
                         created_ip, modified_ip, created_at, updated_at, district_id, state_id,country_id, created_by, modified_by)
VALUES (16, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (17, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (18, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (19, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (20, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (21, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (22, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (23, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (24, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (25, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1),
       (26, 3, 'Bhayendar', '401104', 228, null, null, TRUE, ':0', ':0', now(), now(), 1, 8, 96,1,1);

INSERT INTO mst_mandal (mandal_id, mandal_name, address_id, active, created_at, created_by,updated_at,  modified_by, created_ip, modified_ip)
VALUES (1, 'Shree Vishwakarma Vansh Suthar Charitable Trust', 16, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0'),
       (2, 'Shree Vishwakarma Vansh Suthar Samaj Charitable Trust', 17, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0'),
       (3, 'Shree Vishwakarma Vansh Suthar Samaj', 18, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0'),
       (4, 'Shree Vishwakarma Vansh Suthar Nav Yuvak Mandal', 19, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0'),
       (5, 'Shree Vishwakarma Vansh Suthar Nav Yuvak Mandal', 20, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0'),
       (6, 'Shree Vishwakarma Vansh Suthar Mandal', 21, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0'),
       (7, 'Shree Vishwakarma Vansh Suthar Nav Yuvak Mandal', 22, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0'),
       (8, 'Shree Vishwakarma Vansh Suthar Mandal', 23, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0'),
       (9, 'Shree Vishwakarma Vansh Suthar Mandal', 24, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0'),
       (10, 'Shree Vishwakarma Vansh Suthar Youth Federation', 25, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0'),
       (11, 'Shree Vishwakarma Vansh Suthar Ganesh Utsav Mandal', 26, TRUE, current_timestamp, 1, current_timestamp, 1, ':0',':0');
