INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('app_name', 'श्री विश्वकर्मा वंश सुथार समाज, बारवा', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES 'side_menu_news', 'समाचार', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_state', 'राज्य', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_job_sub_category', 'नौकरी उपश्रेणी', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_education_degree', 'शिक्षा की डिग्री', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_gender', 'लिंग', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES 'side_menu_home', 'घर', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_religion', 'धर्म', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES 'side_menu_family', 'परिवार', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_job_category', 'कार्य श्रेणी', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_marital_status', 'वैवाहिक स्थिति', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES 'side_menu_matrimonial', 'वैवाहिक', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_addiction', 'लत', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_country', 'देश', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_faq_category', 'सामान्य प्रश्न श्रेणी', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES 'side_menu_job', 'काम', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_city_village', 'शहर गाँव', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES 'side_menu_temple', 'मंदिर', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES 'side_menu_event', 'आयोजन', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_job_type', 'कार्य का प्रकार', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_relationship', 'संबंध', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_district', 'ज़िला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_caste', 'जाति', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_job_status', 'कार्य स्थिति', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_gotra', 'गोत्र', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_service', 'सेवा', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES 'side_menu_faq', 'सामान्य प्रश्न', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_business', 'व्यापार', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES 'invalid_login', 'अमान्य लॉगिन', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_raasi', 'राशि', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_contact_type', 'संपर्क प्रकार', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_address_type', 'पता मुद्रलेख', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('error_not_found_admin', 'Admin not found', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('createdByUser', 'निर्माता', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('updatedByUser', 'अपडेटर', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('country', 'देश', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('countryCode', 'कंट्री कोड', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('phoneNumberCode', 'फ़ोन कोड', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_post', 'पद', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('active', 'स्थिति', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action', 'कार्रवाई', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action_edit', 'अपडेटर', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action_logout', 'लॉग आउट', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action_change_password', 'पासवर्ड बदलें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('login_page_title', 'वापसी पर स्वागत है', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('login_sub_title', 'नीचे अपने क्रेडेंशियल के साथ साइन इन करें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('input_user_name', 'उपयोगकर्ता नाम', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('input_password', 'पासवर्ड', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action_login', 'लॉग इन करें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_login', 'लॉग इन', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action_yes', 'हाँ', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action_no', 'नहीं', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action_change_status_title', 'अवस्था बदलो', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action_change_status_description', 'क्या आप निश्चित हैं?, आप इस आइटम की स्थिति बदलना चाहते हैं?', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_addiction', 'लत नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_address_type', 'पता मुद्रलेख नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_business', 'व्यापार नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_caste', 'जाति नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_city_village', 'शहर गाँव नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_contact_type', 'संपर्क प्रकार नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_country', 'देश नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_district', 'ज़िला नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_education_degree', 'शिक्षा की डिग्री नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_event', 'आयोजन नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_family', 'परिवार नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_faq', 'सामान्य प्रश्न नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_faq_category', 'सामान्य प्रश्न श्रेणी नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_gender', 'लिंग नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_gotra', 'गोत्र नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_home', 'घर नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_job', 'काम नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_job_category', 'कार्य श्रेणी नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_job_status', 'कार्य स्थिति नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_job_sub_category', 'नौकरी उपश्रेणी नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_job_type', 'कार्य का प्रकार नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_login', 'लॉग इन नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_marital_status', 'वैवाहिक स्थिति नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_matrimonial', 'वैवाहिक नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_news', 'समाचार नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_post', 'पद नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_raasi', 'राशि नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('seqNo', 'अनु.', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_relationship', 'संबंध नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_religion', 'धर्म नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_service', 'सेवा नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_state', 'राज्य नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_temple', 'मंदिर नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_matrimonial_status', 'वैवाहिक स्थिति', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_matrimonial_status', 'वैवाहिक स्थिति नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_media_type', 'मीडिया प्रकार नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_media_src', 'मीडिया स्रोत नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_media_type', 'मीडिया प्रकार', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_media_src', 'मीडिया स्रोत', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_matrimonial_requested_status', 'वैवाहिक अनुरोध स्थिति', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_matrimonial_requested_status', 'वैवाहिक अनुरोध स्थिति नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_health_parameter', 'स्वास्थ्य पैरामीटर', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_health_parameter', 'स्वास्थ्य पैरामीटर नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('item_not_found_mandal', 'संगठन नहीं मिला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_mandal', 'संगठन', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('success_status_change', 'स्थिति परिवर्तन सफलतापूर्वक', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('updatedAt', 'अद्यतन', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('createdAt', 'बनाया', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('jobCategory', 'कार्य श्रेणी', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('imagePath', 'चित्र', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('jobSubCategory', 'नौकरी उपश्रेणी', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('addressType', 'पता मुद्रलेख', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('business', 'व्यापार', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('caste', 'जाति', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('cityVillage', 'शहर गाँव', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('ContactType', 'संपर्क प्रकार', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('gender', 'लिंग', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('gotra', 'गोत्र', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('healthParameter', 'स्वास्थ्य पैरामीटर', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('jobType', 'कार्य का प्रकार', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('jobStatus', 'कार्य स्थिति', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('faq', 'सामान्य प्रश्न', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('faqCategory', 'सामान्य प्रश्न श्रेणी', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('service', 'सेवा', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('district', 'ज़िला', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('state', 'राज्य', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('addiction', 'लत', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('degree', 'शिक्षा की डिग्री', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('relationship', 'संबंध', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('religion', 'धर्म', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('raasi', 'राशि', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('post', 'पद', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('contactType', 'संपर्क प्रकार', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('maritalStatus', 'वैवाहिक स्थिति', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('matrimonialRequestedStatus', 'वैवाहिक अनुरोध स्थिति', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('matrimonialStatus', 'वैवाहिक स्थिति नहीं मिली', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('templeName', 'मंदिर', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('mandalName', 'संगठन', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('title', 'शीर्षक', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('error_max_length', 'अधिकतम लंबाई', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('error_invalid_number', 'अमान्य संख्या', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('error_min_length', 'न्यूनतम लंबाई', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('error_required', 'आवश्यक', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('error_invalid_date', 'अमान्य दिनांक', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('error_max_value', 'अधिकतम मूल्य', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('error_min_value', 'न्यूनतम मूल्य', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('form_email_id', 'ईमेल आईडी', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('form_phone_number', 'फ़ोन नंबर', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('form_message', 'संदेश', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('form_name', 'नाम', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_contact_us', 'संपर्क करें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_about_us', 'हमारे बारे में', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('side_menu_history', 'इतिहास', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('longitude', 'देशान्तर', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('choose_file', 'फाइलें चुनें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('address_type', 'पता मुद्रलेख', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('city_village', 'शहर/गांव', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action_cancel', 'रद्द करें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('pin_code', 'पिन कोड', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('are_you_sure', 'क्या आपको यकीन है?', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('edit_temple', 'मंदिर संपादित करें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('edit_mandal', 'मंडल संपादित करें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('add_temple', 'मंदिर जोड़ें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('add_mandal', 'मंडल जोड़ें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('progress_file_upload', 'फ़ाइल अपलोड प्रगति पर है', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('address', 'पता', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('choose_attachment', 'फाइलें चुनें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('alert', 'चेतावनी', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('drag_drop_image', 'छवि फ़ाइल को यहां खींचें और छोड़ें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('alert_single_file', 'केवल एकल फ़ाइल अपलोड की अनुमति है, नई फ़ाइल अपलोड करने के लिए कृपया पुरानी फ़ाइल हटा दें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('action_ok', 'ठीक है', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('success_file_upload', 'फ़ाइल सफलतापूर्वक अपलोड की गई', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('drag_drop_pdf', 'पीडीएफ फाइल को यहां खींचें और छोड़ें', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('latitude', 'अक्षांश', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('error_file_upload', 'फ़ाइल अपलोड विफल,  कृपया पुन', 'admin');
INSERT INTO public.mst_label (label_key, label, applicability) VALUES ('form_description', 'विवरण', 'admin');

INSERT INTO public.mst_label (label_key, label, applicability)
VALUES ('success_data_updated', 'डेटा सफलतापूर्वक अपडेट किया गया', 'admin'),
       ('success_data_added', 'डेटा सफलतापूर्वक जोड़ा गया', 'admin');

INSERT INTO public.mst_label (label_key, label, applicability)
VALUES ('error_something_went_wrong', 'त्रुटि कुछ गलत हो गया', 'admin');
