insert into mst_label (label_key, label, applicability)
values ('action_submit', 'Submit', 'admin');

insert into mst_label (label_key, label, applicability)
values
('invalid_login','invalid_login','admin'),
('side_menu_home','side_menu_home','admin'),
('side_menu_news','side_menu_news','admin'),
('side_menu_family','side_menu_family','admin'),
('side_menu_temple','side_menu_temple','admin'),
('side_menu_event','side_menu_event','admin'),
('side_menu_job','side_menu_job','admin'),
('side_menu_mandal','side_menu_mandal','admin'),
('side_menu_matrimonial','side_menu_matrimonial','admin'),
('side_menu_matrimonial_status','side_menu_matrimonial_status','admin'),
('side_menu_matrimonial_requested_status','side_menu_matrimonial_requested_status','admin'),
('side_menu_faq','side_menu_faq','admin'),
('side_menu_job_category','side_menu_job_category','admin'),
('side_menu_job_sub_category','side_menu_job_sub_category','admin'),
('side_menu_job_type','side_menu_job_type','admin'),
('side_menu_job_status','side_menu_job_status','admin'),
('side_menu_faq_category','side_menu_faq_category','admin'),
('side_menu_business','side_menu_business','admin'),
('side_menu_service','side_menu_service','admin'),
('side_menu_city_village','side_menu_city_village','admin'),
('side_menu_state','side_menu_state','admin'),
('side_menu_district','side_menu_district','admin'),
('side_menu_country','side_menu_country','admin'),
('side_menu_addiction','side_menu_addiction','admin'),
('side_menu_education_degree','side_menu_education_degree','admin'),
('side_menu_gender','side_menu_gender','admin'),
('side_menu_caste','side_menu_caste','admin'),
('side_menu_relationship','side_menu_relationship','admin'),
('side_menu_religion','side_menu_religion','admin'),
('side_menu_gotra','side_menu_gotra','admin'),
('side_menu_marital_status','side_menu_marital_status','admin'),
('side_menu_raasi','side_menu_raasi','admin'),
('side_menu_post','side_menu_post','admin'),
('side_menu_address_type','side_menu_address_type','admin'),
('side_menu_contact_type','side_menu_contact_type','admin'),
('side_menu_login','side_menu_login','admin'),
('side_menu_media_type','side_menu_media_type','admin'),
('side_menu_media_src','side_menu_media_src','admin'),
('side_menu_health_parameter','side_menu_health_parameter','admin'),
('side_menu_about_us','side_menu_about_us','admin'),
('side_menu_contact_us','side_menu_contact_us','admin'),
('side_menu_history','side_menu_history','admin'),
('item_not_found_temple','item_not_found_temple','admin'),
('item_not_found_state','item_not_found_state','admin'),
('item_not_found_service','item_not_found_service','admin'),
('item_not_found_religion','item_not_found_religion','admin'),
('item_not_found_relationship','item_not_found_relationship','admin'),
('item_not_found_raasi','item_not_found_raasi','admin'),
('item_not_found_post','item_not_found_post','admin'),
('item_not_found_news','item_not_found_news','admin'),
('item_not_found_matrimonial','item_not_found_matrimonial','admin'),
('item_not_found_matrimonial_status','item_not_found_matrimonial_status','admin'),
('item_not_found_marital_status','item_not_found_marital_status','admin'),
('item_not_found_login','item_not_found_login','admin'),
('item_not_found_job_type','item_not_found_job_type','admin'),
('item_not_found_job_sub_category','item_not_found_job_sub_category','admin'),
('item_not_found_job_status','item_not_found_job_status','admin'),
('item_not_found_job_category','item_not_found_job_category','admin'),
('item_not_found_job','item_not_found_job','admin'),
('item_not_found_home','item_not_found_home','admin'),
('item_not_found_gotra','item_not_found_gotra','admin'),
('item_not_found_gender','item_not_found_gender','admin'),
('item_not_found_faq_category','item_not_found_faq_category','admin'),
('item_not_found_faq','item_not_found_faq','admin'),
('item_not_found_family','item_not_found_family','admin'),
('item_not_found_event','item_not_found_event','admin'),
('item_not_found_education_degree','item_not_found_education_degree','admin'),
('item_not_found_district','item_not_found_district','admin'),
('item_not_found_country','item_not_found_country','admin'),
('item_not_found_contact_type','item_not_found_contact_type','admin'),
('item_not_found_city_village','item_not_found_city_village','admin'),
('item_not_found_caste','item_not_found_caste','admin'),
('item_not_found_business','item_not_found_business','admin'),
('item_not_found_address_type','item_not_found_address_type','admin'),
('item_not_found_addiction','item_not_found_addiction','admin'),
('item_not_found_media_type','item_not_found_media_type','admin'),
('item_not_found_media_src','item_not_found_media_src','admin'),
('item_not_found_matrimonial_requested_status','item_not_found_matrimonial_requested_status','admin'),
('item_not_found_health_parameter','item_not_found_health_parameter','admin'),
('item_not_found_mandal','item_not_found_mandal','admin'),
('item_not_found_page','item_not_found_page','admin'),
('add_mandal','add_mandal','admin'),
('edit_mandal','edit_mandal','admin'),
('add_temple','add_temple','admin'),
('edit_temple','edit_temple','admin'),
('address','address','admin'),
('state','state','admin'),
('district','district','admin'),
('country','country','admin'),
('city_village','city_village','admin'),
('address_type','address_type','admin'),
('app_name','app_name','admin'),
('error_not_found_admin','error_not_found_admin','admin'),
('action_edit','action_edit','admin'),
('action_login','action_login','admin'),
('action_logout','action_logout','admin'),
('action_change_password','action_change_password','admin'),
('action_yes','action_yes','admin'),
('action_no','action_no','admin'),
('action_change_status_title','action_change_status_title','admin'),
('action_change_status_description','action_change_status_description','admin'),
('input_user_name','input_user_name','admin'),
('input_password','input_password','admin'),
('login_page_title','login_page_title','admin'),
('login_sub_title','login_sub_title','admin'),
('success_status_change','success_status_change','admin'),
('error_invalid_date','error_invalid_date','admin'),
('error_invalid_number','error_invalid_number','admin'),
('error_max_length','error_max_length','admin'),
('error_max_value','error_max_value','admin'),
('error_min_length','error_min_length','admin'),
('error_min_value','error_min_value','admin'),
('error_required','error_required','admin'),
('form_name','form_name','admin'),
('form_email_id','form_email_id','admin'),
('form_phone_number','form_phone_number','admin'),
('form_message','form_message','admin');

insert into mst_label (label_key, label, applicability)
values ('pin_code', 'pin_code', 'admin'),
('latitude', 'latitude', 'admin'),
('longitude', 'longitude', 'admin');

insert into mst_label (label_key, label, applicability)
values ('action_cancel', 'action_cancel', 'admin');

insert into mst_label (label_key, label, applicability)
values 
('alert', 'Alert', 'admin'),
('are_you_sure', 'Are you sure?', 'admin'),
('action_ok', 'ok', 'admin'),
('alert_single_file', 'Only single file upload allow, please delete old one for upload new file', 'admin'),
('drag_drop_image', 'Drag and drop image file here', 'admin'),
('drag_drop_pdf', 'Drag and drop pdf file here', 'admin'),
('choose_file', 'Choose file', 'admin'),
('choose_attachment', 'Choose Attachment', 'admin');

insert into mst_label (label_key, label, applicability)
values 
('success_file_upload', 'file uploaded successfully', 'admin'),
('error_file_upload', 'file upload failed, please again', 'admin'),
('progress_file_upload', 'file upload in progress', 'admin');