export enum StringResources {
  APP_TITLE = 'Vishwakarma Vansh Suthar Samaj',

  BACK_TO_PREVIOUS_PAGE = 'Back to Previous Page',

  OK = 'Ok',
  ALERT = 'Alert',
  ARE_YOU_SURE = 'Are you sure?',
  YES = 'Yes',
  NO = 'No',
  SEND_OTP = 'Send Otp',
  CLEAR = 'Clear',
  SEARCH = 'Search',
  SEARCH_FILTER = 'Search Filter',
  SEARCH_TEXT = 'Search text',
  CREATED_AT_FROM_TO_DATE = 'Created From - Created To',
  SAVE = 'Save',
  UPDATE = 'Update',
  CANCEL = 'Cancel',
  DETAILS = 'Details',

  ERROR_SOMETHING_WRONG = 'Oppss! Something went wrong',
  NO_INTERNET_TITLE = 'Oppss! Something went wrong',

  CHOOSE_FILE = 'Choose file',
  TITLE = 'Title',
  DESCRIPTION = 'Description',
  DATE = 'Date',
  TIME = 'Time',
  START_TIME = 'Start Time',
  END_TIME = 'End Time',
  FIRST_NAME = 'First name',
  LAST_NAME = 'Last name',
  MIDDLE_NAME = 'Middle name',
  EMAIL_ID = 'Email Id',
  VILLAGE = 'Village',
  CONTACT_TYPE = 'Contact Type',
  MARITAL_STATUS = 'Marital Status',
  RELIGION = 'Religion',
  GOTRA = 'Gotra',
  RAASI = 'Raasi',
  ARE_YOU_MAGLIK = 'Are you monglik?',
  MAGLIK = 'Maglik',
  HOBBIES = 'Hobbies',
  MONTHLY_INCOME = 'Monthly Income',
  ABOUT = 'About',
  ABOUT_YOUR_SELF = 'About your self',
  CASTE = 'Caste',
  EDUCATION = 'Education',
  GENDER = 'Gender',
  DOB = 'Date of Birth',
  HEIGHT = 'Height',
  WEIGHT = 'Weight',
  KGS = 'Kgs',
  FT_IN = 'Ft. In.',
  PER_MONTH = '/Month',
  ADDRESS = 'Address',
  ADDRESS_TYPE = 'Address Type',
  COUNTRY = 'Country',
  STATE = 'State',
  DISTRICT = 'District',
  LATITUDE = 'Latitude',
  LONGITUDE = 'Longitude',
  CITY_VILLAGE = 'City/Village',
  PIN_CODE = 'Pin Code',
  CONTACT_NUMBER = 'Mobile number',
  PASSWORD = 'Password',
  REPEAT_PASSWORD = 'Repeat Password',
  OTP = 'Otp (One Time Password)',
  START_DATE = 'Start date',
  END_DATE = 'End date',
  ROLE = 'Role',
  STATUS = 'Status',
  APPROVAL_STATUS = 'Approval Status',
  APPROVED_BY = 'Approved By',
  PENDING = 'Pending',
  REASON = 'Reason',
  DRAG_DROP_FILE = 'Drag and drop file here',

  LOGIN = 'Login',
  LOGOUT = 'Logout',
  RESET_PASSWORD = 'Reset Password',
  FORGOT_PASSWORD = 'Forgot Password',
  RESEND_OTP = 'Resend OTP',
  BACK_TO_LOGIN = 'Back to Login',
  FORGOT_PASSWORD_NOT = 'Enter your email id, we will send OTP for reset password on your email id, if you do not receive OTP on inbox then check spam folder also',
  RESET_PASSWORD_NOTE = 'Please check your email id for otp, if you don\'t find email on inbox then please check in spam folder also',

  REQUIRED = 'required',
  IN_VALID_NUMBER = 'Invalid number',
  IN_VALID_DATE = 'Invalid date',
  IN_VALID_MAX_LENGTH = 'max length',
  IN_VALID_MIN_LENGTH = 'min length',
  IN_VALID_WEIGHT = 'invalid weight',
  IN_VALID_HEIGHT = 'invalid height',
  IN_VALID_MAX_VALUE = 'Minimum value should be ',
  IN_VALID_MIN_VALUE = 'Maximum value should be ',
  IN_VALID_LATITUDE = 'Maximum value should be ',
  IN_VALID_LONGITUDE = 'Maximum value should be ',

  DELETE_CONTACT_NUMBER_DESC = 'Are you sure, you want to delete this contact number ?',
  CHANGE_STATUS_DESC = 'Are you sure, you want to change status of this item ?',
  SINGLE_MEDIA_FILE_ALERT = 'Only single file upload allow, please delete old one for upload new file',

  HOME = 'Home',
  MY_PROFILE = 'My Profile',
  ADD_CONTACT_NUMBER = 'Add Contact Number',
  EDIT_CONTACT_NUMBER = 'Edit Contact Number',
  EDIT = 'Edit',
  DELETE = 'Delete',
  ADD = 'Add',
  CREATE_MATRIMONIAL_PROFILE = 'Create Matrimonial Profile',

  ADMIN_LIST = 'Admin',
  ADMIN_CREATE = 'Add Admin',
  ADMIN_EDIT = 'Edit Admin',
  CHANGE_PASSWORD = 'Change Password',
  EDIT_PROFILE = 'Edit Profile',
  SETTING = 'Setting',

  APP_USER_LIST = 'App User',
  APP_USER_CREATE = 'Add App User',
  APP_USER_EDIT = 'Edit App User',

  APP_USER_DEVICE_LIST = 'Device List',
  APP_USER_LOGIN_HISTORY = 'Login History',

  CURRENT_AFFAIR_LIST = 'Current Affair',
  CURRENT_AFFAIR_CREATE = 'Add Current Affair',
  CURRENT_AFFAIR_EDIT = 'Edit Current Affair',
  IS_COMMENT_ALLOW = 'Allow Comments',
  IS_APPROVED = 'Is Approved',
  IS_PUBLISHED = 'Is Published',
  PUBLISHED = 'Published',
  UNPUBLISHED = 'Unpublished',
  APPROVED = 'Approved',
  ACtIVE = 'Active',
  IN_ACTIVE = 'In-Active',
  SOURCE = 'Source',

  EDIT_FAMILY_DETAIL = 'Edit Profile Information',
  ADD_FAMILY_DETAIL = 'Add Profile Information',
  DETAIL = 'Detail',
  EVENT_LIST = 'Event',
  DAY = 'Day',
  AGENDA = 'Agenda',
  EVENT_CREATE = 'Add Event',
  BASIC_DETAILS = 'Basic Details',
  EVENT_EDIT = 'Edit Event',
  EVENT_COORDINATOR = 'Event Coordinator',

  FAMILY_LIST = 'Family',
  FAMILY_CREATE = 'Add Family',
  FAMILY_EDIT = 'Edit Family',
  PERSONAL_DETAIL = 'Personal Information',
  CONTACT_DETAIL = 'Contact Details',
  PROFESSIONAL_DETAIL = 'Business / Service Details',
  ADDRESS_DETAIL = 'Addresses',
  MATRIMONIAL = 'Matrimonial',

  JOB_LIST = 'Job',
  JOB_CREATE = 'Add Job',
  JOB_EDIT = 'Edit Job',

  MATRIMONIAL_LIST = 'Matrimonial',
  MATRIMONIAL_CREATE = 'Add Matrimonial',
  MATRIMONIAL_EDIT = 'Edit Matrimonial',

  TEMPLE_LIST = 'Temple',
  TEMPLE_CREATE = 'Add Temple',
  TEMPLE_EDIT = 'Edit Temple',
  TEMPLE_NAME = 'Temple Name',

  REPORT_INQUIRY = 'Inquiry Report',
  REPORT_PUSH_NOTIFICATION = 'Push Notification Report',

  BUSINESS_LIST = 'Business',
  BUSINESS_CREATE = 'Add Business',
  BUSINESS_EDIT = 'Edit Business',

  SERVICE_LIST = 'Service',
  SERVICE_CREATE = 'Add Service',
  SERVICE_EDIT = 'Edit Service',

  COUNTRY_LIST = 'Country',
  COUNTRY_CREATE = 'Add Country',
  COUNTRY_EDIT = 'Edit Country',

  STATE_LIST = 'State',
  STATE_CREATE = 'Add State',
  STATE_EDIT = 'Edit State',

  DISTRICT_LIST = 'District',
  DISTRICT_CREATE = 'Add District',
  DISTRICT_EDIT = 'Edit District',

  CITY_VILLAGE_LIST = 'City Village',
  CITY_VILLAGE_CREATE = 'Add City Village',
  CITY_VILLAGE_EDIT = 'Edit City Village',

  GENDER_LIST = 'Gender',
  GENDER_CREATE = 'Add Gender',
  GENDER_EDIT = 'Edit Gender',
  ADDICTION_LIST = 'Addiction',
  ADDICTION_CREATE = 'Add Addiction',
  ADDICTION_EDIT = 'Edit Addiction',
  RELATION_SHIP_LIST = 'Relation-Ship',
  RELATION_SHIP_CREATE = 'Add Relation-Ship',
  RELATION_SHIP_EDIT = 'Edit Relation-Ship',
  RELIGION_LIST = 'Religion',
  RELIGION_CREATE = 'Add Religion',
  RELIGION_EDIT = 'Edit Religion',
  GOTRA_LIST = 'Gotra',
  GOTRA_CREATE = 'Add Gotra',
  GOTRA_EDIT = 'Edit Gotra',

  POST_LIST = 'Post',
  POST_CREATE = 'Add Post',
  POST_EDIT = 'Edit Post',

  JOB_TYPE_LIST = 'Job Type',
  JOB_TYPE_CREATE = 'Add Job Type',
  JOB_TYPE_EDIT = 'Edit Job Type',
  JOB_CATEGORY_LIST = 'Job Category',
  JOB_CATEGORY_CREATE = 'Add Job Category',
  JOB_CATEGORY_EDIT = 'Edit Job Category',
  JOB_SUB_CATEGORY_LIST = 'Job Sub-Category',
  JOB_SUB_CATEGORY_CREATE = 'Add Job Sub-Category',
  JOB_SUB_CATEGORY_EDIT = 'Edit Job Sub-Category',

  FAQ_CATEGORY_LIST = 'Faq Category',
  FAQ_CATEGORY_CREATE = 'Add Faq Category',
  FAQ_CATEGORY_EDIT = 'Edit Faq Category',

  LEGAL_PAGE_LIST = 'Legal Pages',
  LEGAL_PAGE_CREATE = 'Add Legal Page',
  LEGAL_PAGE_EDIT = 'Edit Legal Page',

  CONFIG_PARAMETER_LIST = 'Configuration',
  CONFIG_PARAMETER_CREATE = 'Add Configuration',
  CONFIG_PARAMETER_EDIT = 'Edit Configuration',

  FAQ_LIST = 'Faqs',
  FAQ_CREATE = 'Add Faqs',
  FAQ_EDIT = 'Edit Faqs',

  MANDAL_LIST = 'Mandal',
  MANDAL_CREATE = 'Add Mandal',
  MANDAL_EDIT = 'Edit Mandal',
  MANDAL_MEMBER_MANAGE = 'Mandal Members',
  MANDAL_NAME='Mandal Name',

  TRUSTEE_LIST = 'Trustee',
  TRUSTEE_CREATE = 'Add Trustee',
  TRUSTEE_EDIT = 'Edit Trustee'
}
