export enum LabelKey {
  INVALID_LOGIN = 'invalid_login',
  SIDE_MENU_HOME = 'side_menu_home',
  SIDE_MENU_NEWS = 'side_menu_news',
  SIDE_MENU_FAMILY = 'side_menu_family',
  SIDE_MENU_TEMPLE = 'side_menu_temple',
  SIDE_MENU_EVENT = 'side_menu_event',
  SIDE_MENU_JOB = 'side_menu_job',
  SIDE_MENU_MANDAL = 'side_menu_mandal',
  SIDE_MENU_MATRIMONIAL = 'side_menu_matrimonial',
  SIDE_MENU_MATRIMONIAL_STATUS = 'side_menu_matrimonial_status',
  SIDE_MENU_MATRIMONIAL_REQUESTED_STATUS = 'side_menu_matrimonial_requested_status',
  SIDE_MENU_FAQ = 'side_menu_faq',
  SIDE_MENU_JOB_CATEGORY = 'side_menu_job_category',
  SIDE_MENU_JOB_SUB_CATEGORY = 'side_menu_job_sub_category',
  SIDE_MENU_JOB_TYPE = 'side_menu_job_type',
  SIDE_MENU_JOB_STATUS = 'side_menu_job_status',
  SIDE_MENU_FAQ_CATEGORY = 'side_menu_faq_category',
  SIDE_MENU_BUSINESS = 'side_menu_business',
  SIDE_MENU_SERVICE = 'side_menu_service',
  SIDE_MENU_CITY_VILLAGE = 'side_menu_city_village',
  SIDE_MENU_STATE = 'side_menu_state',
  SIDE_MENU_DISTRICT = 'side_menu_district',
  SIDE_MENU_COUNTRY = 'side_menu_country',
  SIDE_MENU_ADDICTION = 'side_menu_addiction',
  SIDE_MENU_EDUCATION_DEGREE = 'side_menu_education_degree',
  SIDE_MENU_GENDER = 'side_menu_gender',
  SIDE_MENU_CASTE = 'side_menu_caste',
  SIDE_MENU_RELATIONSHIP = 'side_menu_relationship',
  SIDE_MENU_RELIGION = 'side_menu_religion',
  SIDE_MENU_GOTRA = 'side_menu_gotra',
  SIDE_MENU_MARITAL_STATUS = 'side_menu_marital_status',
  SIDE_MENU_RAASI = 'side_menu_raasi',
  SIDE_MENU_POST = 'side_menu_post',
  SIDE_MENU_ADDRESS_TYPE = 'side_menu_address_type',
  SIDE_MENU_CONTACT_TYPE = 'side_menu_contact_type',
  SIDE_MENU_LOGIN = 'side_menu_login',
  SIDE_MENU_MEDIA_TYPE = 'side_menu_media_type',
  SIDE_MENU_MEDIA_SRC = 'side_menu_media_src',
  SIDE_MENU_HEALTH_PARAMETER = 'side_menu_health_parameter',
  SIDE_MENU_ABOUT_US = 'side_menu_about_us',
  SIDE_MENU_CONTACT_US = 'side_menu_contact_us',
  SIDE_MENU_HISTORY = 'side_menu_history',

  ITEM_NOT_FOUND_TEMPLE = 'item_not_found_temple',
  ITEM_NOT_FOUND_STATE = 'item_not_found_state',
  ITEM_NOT_FOUND_SERVICE = 'item_not_found_service',
  ITEM_NOT_FOUND_RELIGION = 'item_not_found_religion',
  ITEM_NOT_FOUND_RELATIONSHIP = 'item_not_found_relationship',
  ITEM_NOT_FOUND_RAASI = 'item_not_found_raasi',
  ITEM_NOT_FOUND_POST = 'item_not_found_post',
  ITEM_NOT_FOUND_NEWS = 'item_not_found_news',
  ITEM_NOT_FOUND_MATRIMONIAL = 'item_not_found_matrimonial',
  ITEM_NOT_FOUND_MATRIMONIAL_STATUS = 'item_not_found_matrimonial_status',
  ITEM_NOT_FOUND_MARITAL_STATUS = 'item_not_found_marital_status',
  ITEM_NOT_FOUND_LOGIN = 'item_not_found_login',
  ITEM_NOT_FOUND_JOB_TYPE = 'item_not_found_job_type',
  ITEM_NOT_FOUND_JOB_SUB_CATEGORY = 'item_not_found_job_sub_category',
  ITEM_NOT_FOUND_JOB_STATUS = 'item_not_found_job_status',
  ITEM_NOT_FOUND_JOB_CATEGORY = 'item_not_found_job_category',
  ITEM_NOT_FOUND_JOB = 'item_not_found_job',
  ITEM_NOT_FOUND_HOME = 'item_not_found_home',
  ITEM_NOT_FOUND_GOTRA = 'item_not_found_gotra',
  ITEM_NOT_FOUND_GENDER = 'item_not_found_gender',
  ITEM_NOT_FOUND_FAQ_CATEGORY = 'item_not_found_faq_category',
  ITEM_NOT_FOUND_FAQ = 'item_not_found_faq',
  ITEM_NOT_FOUND_FAMILY = 'item_not_found_family',
  ITEM_NOT_FOUND_EVENT = 'item_not_found_event',
  ITEM_NOT_FOUND_EDUCATION_DEGREE = 'item_not_found_education_degree',
  ITEM_NOT_FOUND_DISTRICT = 'item_not_found_district',
  ITEM_NOT_FOUND_COUNTRY = 'item_not_found_country',
  ITEM_NOT_FOUND_CONTACT_TYPE = 'item_not_found_contact_type',
  ITEM_NOT_FOUND_CITY_VILLAGE = 'item_not_found_city_village',
  ITEM_NOT_FOUND_CASTE = 'item_not_found_caste',
  ITEM_NOT_FOUND_BUSINESS = 'item_not_found_business',
  ITEM_NOT_FOUND_ADDRESS_TYPE = 'item_not_found_address_type',
  ITEM_NOT_FOUND_ADDICTION = 'item_not_found_addiction',
  ITEM_NOT_FOUND_MEDIA_TYPE = 'item_not_found_media_type',
  ITEM_NOT_FOUND_MEDIA_SRC = 'item_not_found_media_src',
  ITEM_NOT_FOUND_MATRIMONIAL_REQUESTED_STATUS = 'item_not_found_matrimonial_requested_status',
  ITEM_NOT_FOUND_HEALTH_PARAMETER = 'item_not_found_health_parameter',
  ITEM_NOT_FOUND_MANDAL = 'item_not_found_mandal',
  ITEM_NOT_FOUND_PAGE = 'item_not_found_page',

  APP_NAME = 'app_name',
  ERROR_NOT_FOUND_ADMIN = 'error_not_found_admin',

  ACTION_SUBMIT = 'action_submit',
  ACTION_EDIT = 'action_edit',
  ACTION_CANCEL = 'action_cancel',
  ACTION_LOGIN = 'action_login',
  ACTION_LOGOUT = 'action_logout',
  ACTION_CHANGE_PASSWORD = 'action_change_password',
  ACTION_YES = 'action_yes',
  ACTION_NO = 'action_no',
  ACTION_CHANGE_STATUS_TITLE = 'action_change_status_title',
  ACTION_CHANGE_STATUS_DESCRIPTION = 'action_change_status_description',
  ACTION_OK = 'action_ok',

  INPUT_USER_NAME = 'input_user_name',
  INPUT_PASSWORD = 'input_password',

  LOGIN_PAGE_TITLE = 'login_page_title',
  LOGIN_SUB_TITLE = 'login_sub_title',
  SUCCESS_STATUS_CHANGE = 'success_status_change',

  ERROR_IN_VALID_DATE = 'error_invalid_date',
  ERROR_IN_VALID_NUMBER = 'error_invalid_number',
  ERROR_IN_VALID_MAX_LENGTH = 'error_max_length',
  ERROR_IN_VALID_MAX_VALUE = 'error_max_value',
  ERROR_IN_VALID_MIN_LENGTH = 'error_min_length',
  ERROR_IN_VALID_MIN_VALUE = 'error_min_value',
  ERROR_REQUIRED = 'error_required',

  FORM_NAME = 'form_name',
  FORM_EMAIL_ID = 'form_email_id',
  FORM_PHONE_NUMBER = 'form_phone_number',
  FORM_MESSAGE = 'form_message',
  FORM_DESCRIPTION = 'form_description',

  ADD_MANDAL = 'add_mandal',
  EDIT_MANDAL = 'edit_mandal',

  ADD_TEMPLE = 'add_temple',
  EDIT_TEMPLE = 'edit_temple',

  ADDRESS = 'address',
  STATE = 'state',
  DISTRICT = 'district',
  COUNTRY = 'country',
  CITY_VILLAGE = 'city_village',
  ADDRESS_TYPE = 'address_type',
  PIN_CODE = 'pin_code',
  LATITUDE = 'latitude',
  LONGITUDE = 'longitude',

  ALERT = 'alert',
  ARE_YOU_SURE = 'are_you_sure',

  SINGLE_MEDIA_FILE_ALERT = 'alert_single_file',
  DRAG_DROP_IMAGE_FILE = 'drag_drop_image',
  DRAG_DROP_PDF_FILE = 'drag_drop_pdf',
  CHOOSE_FILE = 'choose_file',
  CHOOSE_ATTACHMENT = 'choose_attachment',

  SUCCESS_FILE_UPLOADED = 'success_file_upload',
  SUCCESS_FILE_ERROR = 'error_file_upload',
  SUCCESS_FILE_PROGRESS = 'progress_file_upload',
}
