export enum MediaForEnum {
  BANNER = 'banner',
  TEMPLE = 'temple',
  MANDAL = 'mandal',
  EVENT = 'event',
  FACILITY = 'facility',
  ADMIN = 'admin',
  FAMILY = 'family',
  ADDICTION = 'addiction',
  BUSINESS = 'business',
  CASTE = 'caste',
  EDUCATION_DEGREE = 'education_degree',
  MEDIA_FOLDER = 'media-files',
  UPLOADS = 'uploads',

  CONTACT_TYPE = 'contact_type',
  GENDER = 'gender',
  ADDRESS_TYPE = 'address_type',
  POST = 'post',
  RAASI = 'raasi',
  RELATIONSHIP = 'relationship',
  MATRIMONIAL_STATUS = 'matrimonial_status',
  GOTRA = 'gotra',
  JOB_CATEGORY = 'job_category',
  JOB_SUB_CATEGORY = 'job_sub_category',
  MATRIMONIAL_REQUESTED_STATUS = 'matrimonial_requested_status',
  MARITAL_STATUS = 'marital_status',
  JOB_TYPE = 'job_type',
  JOB_STATUS = 'job_status',
  RELIGION = 'religion',
  SERVICE = 'service',
  PAGE = 'page',
}
