export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY';
export const AUTH_OTP_REPOSITORY = 'AUTH_OTP_REPOSITORY';

export const EVENT_REPOSITORY = 'EVENT_REPOSITORY';
export const EVENT_COORDINATE_REPOSITORY = 'EVENT_COORDINATE_REPOSITORY';
export const EVENT_INTEREST_MEMBER_REPOSITORY = 'EVENT_INTEREST_MEMBER_REPOSITORY';

export const CURRENT_AFFAIR_REPOSITORY = 'CURRENT_AFFAIR_REPOSITORY';

export const ADDRESS_REPOSITORY = 'ADDRESS_REPOSITORY';

export const IS_DEV = true;
export const OTP_LENGTH = 6;
export const DEFAULT_PAGE_SIZE = 15;

export const MANDAL_REPOSITORY = 'MANDAL_REPOSITORY';
export const MANDAL_MEMBER_REPOSITORY = 'MANDAL_MEMBER_REPOSITORY';
export const TRUSTEE_REPOSITORY = 'TRUSTEE_REPOSITORY';
export const TEMPLE_REPOSITORY = 'TEMPLE_REPOSITORY';
export const FAQ_CATEGORY_REPOSITORY = 'FAQ_CATEGORY_REPOSITORY';
export const FAQ_REPOSITORY = 'FAQ_REPOSITORY';
export const LEGAL_PAGE_REPOSITORY = 'LEGAL_PAGE_REPOSITORY';
export const INQUIRY_REPOSITORY = 'INQUIRY_REPOSITORY';

export const DEFAULT_DATE_FORMAT = 'DD-MMM-YYYY';
export const DEFAULT_TIME_FORMAT = 'h:mm:ss';
export const DEFAULT_DATE_TIME_FORMAT = 15;

export const T_C_PAGE = 1;
export const PP_PAGE = 2;