import {MediaFolderEnum} from "../enums/media-folder-enum";

export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const ADMIN_REPOSITORY = 'ADMIN_REPOSITORY';
export const ADMIN_LOGIN_HISTORY_REPOSITORY = 'ADMIN_LOGIN_HISTORY_REPOSITORY';
export const ADMIN_FORGOT_PASSWORD_REPOSITORY = 'ADMIN_FORGOT_PASSWORD_REPOSITORY';

export const EVENT_REPOSITORY = 'EVENT_REPOSITORY';
export const EVENT_COORDINATE_REPOSITORY = 'EVENT_COORDINATE_REPOSITORY';
export const EVENT_INTEREST_MEMBER_REPOSITORY = 'EVENT_INTEREST_MEMBER_REPOSITORY';

export const FAMILY_REPOSITORY = 'FAMILY_REPOSITORY';
export const FAMILY_PROFILE_REPOSITORY = 'FAMILY_PROFILE_REPOSITORY';
export const FAMILY_EDUCATION_REPOSITORY = 'FAMILY_EDUCATION_REPOSITORY';
export const FAMILY_BUSINESS_REPOSITORY = 'FAMILY_BUSINESS_REPOSITORY';
export const FAMILY_BUSINESS_MAPPING_REPOSITORY = 'FAMILY_BUSINESS_MAPPING_REPOSITORY';
export const FAMILY_CONTACT_NUMBER_REPOSITORY = 'FAMILY_CONTACT_NUMBER_REPOSITORY';
export const FAMILY_ADDICTION_REPOSITORY = 'FAMILY_ADDICTION_REPOSITORY';
export const FAMILY_SERVICE_REPOSITORY = 'FAMILY_SERVICE_REPOSITORY';
export const FAMILY_RELATIONSHIP_REPOSITORY = 'FAMILY_RELATIONSHIP_REPOSITORY';

export const JOB_REPOSITORY = 'JOB_REPOSITORY';
export const CURRENT_AFFAIR_REPOSITORY = 'CURRENT_AFFAIR_REPOSITORY';
export const ADMIN_USER_REPOSITORY = 'ADMIN_USER_REPOSITORY';
export const ADMIN_ROLE_REPOSITORY = 'ADMIN_ROLE_REPOSITORY';

export const ADDRESS_REPOSITORY = 'ADDRESS_REPOSITORY';
export const ADDRESS_TYPE_REPOSITORY = 'ADDRESS_TYPE_REPOSITORY';
export const CONTACT_TYPE_REPOSITORY = 'CONTACT_TYPE_REPOSITORY';
export const RAASI_REPOSITORY = 'RAASI_REPOSITORY';

export const IS_DEV = true;
export const OTP_LENGTH = 6;
export const DEFAULT_PAGE_SIZE = 15;

export const MANDAL_REPOSITORY = 'MANDAL_REPOSITORY';
export const MANDAL_MEMBER_REPOSITORY = 'MANDAL_MEMBER_REPOSITORY';
export const TRUSTEE_REPOSITORY = 'TRUSTEE_REPOSITORY';

export const TEMPLE_REPOSITORY = 'TEMPLE_REPOSITORY';

export const FAQ_CATEGORY_REPOSITORY = 'FAQ_CATEGORY_REPOSITORY';
export const FAQ_REPOSITORY = 'FAQ_REPOSITORY';

export const LEGAL_PAGE_REPOSITORY = 'LEGAL_PAGE_REPOSITORY';

export const INQUIRY_REPOSITORY = 'INQUIRY_REPOSITORY';

export const ADDICTION_REPOSITORY = 'ADDICTION_REPOSITORY';
export const BUSINESS_REPOSITORY = 'BUSINESS_REPOSITORY';
export const CITY_VILLAGE_REPOSITORY = 'CITY_VILLAGE_REPOSITORY';
export const DISTRICT_REPOSITORY = 'DISTRICT_REPOSITORY';
export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
export const STATE_REPOSITORY = 'STATE_REPOSITORY';
export const JOB_CATEGORY_REPOSITORY = 'JOB_CATEGORY_REPOSITORY';
export const JOB_TYPE_REPOSITORY = 'JOB_TYPE_REPOSITORY';
export const JOB_SUB_CATEGORY_REPOSITORY = 'JOB_SUB_CATEGORY_REPOSITORY';
export const GENDER_REPOSITORY = 'GENDER_REPOSITORY';
export const GOTRA_REPOSITORY = 'GOTRA_REPOSITORY';
export const EDUCATION_DEGREE_REPOSITORY = 'EDUCATION_DEGREE_REPOSITORY';
export const RELIGION_REPOSITORY = 'RELIGION_REPOSITORY';
export const RELATION_REPOSITORY = 'RELATION_REPOSITORY';
export const POST_REPOSITORY = 'POST_REPOSITORY';
export const SERVICE_REPOSITORY = 'SERVICE_REPOSITORY';
export const MARITAL_STATUS_REPOSITORY = 'MARITAL_STATUS_REPOSITORY';

export const MATRIMONIAL_REPOSITORY = 'MATRIMONIAL_REPOSITORY';

export const APP_USER_REPOSITORY = 'APP_USER_REPOSITORY';
export const APP_USER_DEVICE_REPOSITORY = 'APP_USER_DEVICE_REPOSITORY';
export const APP_USER_LOGIN_HISTORY_REPOSITORY = 'APP_USER_LOGIN_HISTORY_REPOSITORY';

export const LOG_ERROR = 'LOG_ERROR';

export const DEFAULT_DATE_FORMAT = 'DD-MMM-YYYY';
export const DEFAULT_DATE_TIME_FORMAT = 'DD-MMM-YYYY h:mm:ss a';
export const DB_DATE_TIME_FORMAT = 'YYYY-MM-DD h:mm:ss a';
export const DB_DATE_FORMAT = 'YYYY-MM-DD';
export const DEFAULT_TIME_FORMAT = 'h:mm:ss';
export const DISPLAY_TIME_FORMAT = 'h:mm a';

export const T_C_PAGE = 1;
export const PP_PAGE = 2;
export const RJ_STATE = 8;
export const IN_COUNTRY = 96;

export const IMAGE_PATH = 'media-files/';
export const APP_USER_IMAGE_PATH = `${IMAGE_PATH}${MediaFolderEnum.APP_USER}/`;
export const ADMIN_IMAGE_PATH = `${IMAGE_PATH}${MediaFolderEnum.ADMIN}/`;
export const FAMILY_IMAGE_PATH = `${IMAGE_PATH}${MediaFolderEnum.FAMILY}/`;
export const EVENT_IMAGE_PATH = `${IMAGE_PATH}${MediaFolderEnum.EVENT}/`;
export const NEWS_IMAGE_PATH = `${IMAGE_PATH}${MediaFolderEnum.NEWS}/`;
export const TEMPLE_IMAGE_PATH = `${IMAGE_PATH}${MediaFolderEnum.TEMPLE}/`;
export const GALLERY_IMAGE_PATH = `${IMAGE_PATH}${MediaFolderEnum.GALLERY}/`;
export const JOB_IMAGE_PATH = `${IMAGE_PATH}${MediaFolderEnum.JOB}/`;

export const ADMIN_USER_SHORT_INFO_ATTRIBUTE = ['adminId','firstName', 'lastName', 'imagePath', 'cityVillageId'];

export const DEFAULT_CONTACT_NUMBER_COUNTRY_CODE = '+91';
